<script setup lang="ts">
// @ts-nocheck
import { computed, reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import '../styles/admin-config.css'

type MenuNode={id:number;parentId:number|null;name:string;type:'DIRECTORY'|'PAGE'|'ACTION';permission:string;component:string;status:'ACTIVE'|'INACTIVE';createdAt:string;children?:MenuNode[]}
const route=useRoute(), isMenu=computed(()=>route.path==='/system/menus'), keyword=ref(''), status=ref(''), dialog=ref(false), drawer=ref(false), current=ref<any>({}), form=reactive<any>({})
const menus=ref<MenuNode[]>([
  {id:1,parentId:null,name:'首页',type:'PAGE',permission:'dashboard:view',component:'DashboardView',status:'ACTIVE',createdAt:'2026-08-01 09:00:00'},
  {id:2,parentId:null,name:'线索中心',type:'DIRECTORY',permission:'',component:'',status:'ACTIVE',createdAt:'2026-08-01 09:02:00',children:[{id:21,parentId:2,name:'引流线索',type:'PAGE',permission:'lead:drainage:view',component:'LeadsView',status:'ACTIVE',createdAt:'2026-08-01 09:03:00'}]},
  {id:3,parentId:null,name:'客户中心',type:'DIRECTORY',permission:'',component:'',status:'ACTIVE',createdAt:'2026-08-01 09:05:00',children:[{id:31,parentId:3,name:'客户列表',type:'PAGE',permission:'customer:list:view',component:'CustomersView',status:'ACTIVE',createdAt:'2026-08-01 09:06:00'}]},
  {id:4,parentId:null,name:'订单中心',type:'DIRECTORY',permission:'',component:'',status:'ACTIVE',createdAt:'2026-08-01 09:08:00'},
  {id:5,parentId:null,name:'系统管理',type:'DIRECTORY',permission:'',component:'',status:'ACTIVE',createdAt:'2026-08-01 09:10:00',children:[{id:51,parentId:5,name:'组织管理',type:'PAGE',permission:'system:org:view',component:'SystemView',status:'ACTIVE',createdAt:'2026-08-01 09:11:00'},{id:52,parentId:5,name:'菜单管理',type:'PAGE',permission:'system:menu:view',component:'AdminConfigView',status:'ACTIVE',createdAt:'2026-08-01 09:12:00'}]}
])
const exceptions=ref([
  {id:'EX20260817001932',url:'https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get',code:'84061',message:'不存在外部联系人的关系',type:'客户联系',time:'2026-08-17 00:19:32',count:2,status:'PENDING',trace:'7bf2-84061-a19c'},
  {id:'EX20260817001345',url:'https://qyapi.weixin.qq.com/cgi-bin/corp/get_join_qrcode',code:'48002',message:'API接口无权限调用',type:'通讯录授权',time:'2026-08-17 00:13:45',count:4,status:'PENDING',trace:'15ad-48002-57fe'},
  {id:'EX20260816235718',url:'https://qyapi.weixin.qq.com/cgi-bin/corp/get_join_qrcode',code:'48002',message:'API接口无权限调用',type:'通讯录授权',time:'2026-08-16 23:57:18',count:1,status:'RETRYING',trace:'550a-48002-201d'},
  {id:'EX20260816234932',url:'https://qyapi.weixin.qq.com/cgi-bin/externalcontact/get',code:'84061',message:'不存在外部联系人的关系',type:'客户联系',time:'2026-08-16 23:49:32',count:3,status:'PENDING',trace:'f721-84061-10cd'},
  {id:'EX20260816234619',url:'https://qyapi.weixin.qq.com/cgi-bin/corp/get_join_qrcode',code:'48002',message:'API接口无权限调用',type:'通讯录授权',time:'2026-08-16 23:46:19',count:5,status:'MANUAL',trace:'91ef-48002-c209'}
])
const dateRange=ref<string[]>([]), exceptionStatus=ref('')
const filteredMenus=computed(()=>{const term=keyword.value.trim().toLowerCase();const filter=(rows:MenuNode[]):MenuNode[]=>rows.flatMap(row=>{const children=filter(row.children||[]);return((!status.value||row.status===status.value)&&(!term||`${row.name}${row.permission}${row.component}`.toLowerCase().includes(term)))||children.length?[{...row,children}]:[]});return filter(menus.value)})
const filteredExceptions=computed(()=>{const term=keyword.value.trim().toLowerCase();return exceptions.value.filter(row=>(!exceptionStatus.value||row.status===exceptionStatus.value)&&(!term||`${row.url}${row.code}${row.message}${row.id}`.toLowerCase().includes(term)))})
function reset(){keyword.value='';status.value='';exceptionStatus.value='';dateRange.value=[]}
function openMenu(row?:MenuNode,parent?:MenuNode){current.value=row||{};Object.keys(form).forEach(key=>delete form[key]);Object.assign(form,row||{parentId:parent?.id||null,name:'',type:parent?'PAGE':'DIRECTORY',permission:'',component:'',status:'ACTIVE'});dialog.value=true}
function saveMenu(){if(!form.name){ElMessage.warning('请输入菜单名称');return}dialog.value=false;ElMessage.success(form.id?'菜单已更新':'菜单已新增')}
async function removeMenu(row:MenuNode){if(row.children?.length){await ElMessageBox.alert(`“${row.name}”存在 ${row.children.length} 个下级菜单，请先处理下级。`,'暂时无法删除',{type:'warning'});return}ElMessage.success('菜单已删除（演示）')}
function showException(row:any){current.value=row;drawer.value=true}
function processException(action:string){ElMessage.success(`${action}任务已提交`)}
</script>

<template><section class="page admin-config-page">
  <PageHeader eyebrow="HESHU BOSS · SYSTEM ADMIN" :title="isMenu?'菜单管理':'异常中心'" :description="isMenu?'配置合数BOSS动态菜单、页面路由及操作权限标识。':'集中查询企微接口、回调与数据同步异常，并形成可追踪的处理闭环。'"><el-button v-if="isMenu" type="primary" @click="openMenu()">新增菜单</el-button><el-tag v-else type="warning">企微异常</el-tag></PageHeader>
  <template v-if="isMenu"><div class="surface admin-filter"><el-form inline><el-form-item label="菜单名称"><el-input v-model="keyword" clearable placeholder="输入名称、权限标识或组件"/></el-form-item><el-form-item label="菜单状态"><el-select v-model="status" clearable placeholder="请选择"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item><el-form-item><el-button type="primary">搜索</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></div><main class="surface admin-table"><div class="admin-table-head"><el-button type="primary" @click="openMenu()">新增</el-button><span>目录、页面、操作权限按树形关系维护</span></div><el-table :data="filteredMenus" row-key="id" default-expand-all><el-table-column prop="name" label="菜单名称" min-width="210"/><el-table-column prop="type" label="菜单类型" width="110"><template #default="{row}">{{ {DIRECTORY:'目录',PAGE:'页面',ACTION:'操作'}[row.type] }}</template></el-table-column><el-table-column prop="permission" label="权限标识" min-width="190"><template #default="{row}"><code>{{ row.permission||'—' }}</code></template></el-table-column><el-table-column prop="component" label="组件路径" min-width="180"><template #default="{row}">{{ row.component||'—' }}</template></el-table-column><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{ row.status==='ACTIVE'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="创建时间" width="170"/><el-table-column label="操作" width="180" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openMenu(row)">修改</el-button><el-button link type="primary" :disabled="row.type==='ACTION'" @click="openMenu(undefined,row)">新增</el-button><el-button link type="danger" @click="removeMenu(row)">删除</el-button></template></el-table-column></el-table></main></template>
  <template v-else><div class="exception-metrics"><article><span>待处理</span><b>{{ exceptions.filter(i=>i.status==='PENDING').length }}</b><small>需确认权限或数据关系</small></article><article><span>重试中</span><b>{{ exceptions.filter(i=>i.status==='RETRYING').length }}</b><small>按幂等策略自动执行</small></article><article><span>转人工</span><b>{{ exceptions.filter(i=>i.status==='MANUAL').length }}</b><small>等待负责人处理</small></article></div><div class="surface admin-filter exception-filter"><el-form inline><el-form-item label="请求/异常"><el-input v-model="keyword" clearable placeholder="请求地址、异常码或编号"/></el-form-item><el-form-item label="请求时间"><el-date-picker v-model="dateRange" type="daterange" start-placeholder="开始日期" end-placeholder="结束日期"/></el-form-item><el-form-item label="处理状态"><el-select v-model="exceptionStatus" clearable placeholder="全部状态"><el-option label="待处理" value="PENDING"/><el-option label="重试中" value="RETRYING"/><el-option label="转人工" value="MANUAL"/></el-select></el-form-item><el-form-item><el-button type="primary">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></div><main class="surface admin-table"><el-table :data="filteredExceptions"><el-table-column prop="id" label="异常编号" width="165"/><el-table-column prop="url" label="请求地址" min-width="330" show-overflow-tooltip/><el-table-column prop="code" label="异常码" width="100"/><el-table-column prop="message" label="异常信息" min-width="190"/><el-table-column prop="type" label="业务类型" width="110"/><el-table-column prop="count" label="次数" width="72" align="center"/><el-table-column prop="time" label="最近请求时间" width="175"/><el-table-column prop="status" label="状态" width="95"><template #default="{row}"><el-tag :type="row.status==='PENDING'?'danger':row.status==='RETRYING'?'warning':'info'">{{ {PENDING:'待处理',RETRYING:'重试中',MANUAL:'转人工'}[row.status] }}</el-tag></template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="{row}"><el-button link type="primary" @click="showException(row)">详情</el-button></template></el-table-column></el-table><div class="employee-pagination"><span>共 {{ filteredExceptions.length }} 条异常记录</span><el-pagination background layout="prev, pager, next, sizes, total" :total="filteredExceptions.length" :page-size="10"/></div></main></template>
  <el-dialog v-model="dialog" :title="form.id?'修改菜单':'新增菜单'" width="620px"><el-form :model="form" label-position="top"><div class="form-grid"><el-form-item label="上级菜单"><el-select v-model="form.parentId" clearable style="width:100%"><el-option label="无（一级菜单）" :value="null"/><el-option v-for="item in menus" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="菜单类型"><el-select v-model="form.type" style="width:100%"><el-option label="目录" value="DIRECTORY"/><el-option label="页面" value="PAGE"/><el-option label="操作权限" value="ACTION"/></el-select></el-form-item><el-form-item label="菜单名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="权限标识"><el-input v-model="form.permission" placeholder="例如 system:menu:view"/></el-form-item><el-form-item label="组件路径"><el-input v-model="form.component" :disabled="form.type!=='PAGE'"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio value="ACTIVE">启用</el-radio><el-radio value="INACTIVE">停用</el-radio></el-radio-group></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="saveMenu">保存</el-button></template></el-dialog>
  <el-drawer v-model="drawer" title="异常详情" size="600px"><div class="exception-title"><span>{{ current.code }}</span><div><h3>{{ current.message }}</h3><p>{{ current.id }} · {{ current.type }}</p></div></div><el-descriptions :column="1" border><el-descriptions-item label="请求地址">{{ current.url }}</el-descriptions-item><el-descriptions-item label="最近发生">{{ current.time }}</el-descriptions-item><el-descriptions-item label="累计次数">{{ current.count }}</el-descriptions-item><el-descriptions-item label="追踪号">{{ current.trace }}</el-descriptions-item><el-descriptions-item label="请求摘要">CorpID：ww****21；凭证及敏感参数已隐藏</el-descriptions-item><el-descriptions-item label="处理建议">检查企微应用授权范围及外部联系人关系后重试。</el-descriptions-item></el-descriptions><div class="drawer-footer"><el-button @click="processException('忽略')">忽略</el-button><el-button @click="processException('转人工')">转人工</el-button><el-button type="primary" @click="processException('重试')">立即重试</el-button></div></el-drawer>
</section></template>
