<script setup lang="ts">
import {onMounted,ref} from 'vue';import http from '../api/http';import PageHeader from '../components/PageHeader.vue';import StatePanel from '../components/StatePanel.vue'
const rows=ref<any[]>([]),loading=ref(false),error=ref(''),grade=ref(''),dialog=ref(false),form=ref({name:'',mobile:'',unionId:'',ownerName:'王老师'})
async function load(){loading.value=true;try{const r:any=await http.get('/customers',{params:{grade:grade.value||undefined}});rows.value=r.data}catch(e:any){error.value=e.message}finally{loading.value=false}}onMounted(load)
async function create(){await http.post('/customers',form.value);dialog.value=false;form.value={name:'',mobile:'',unionId:'',ownerName:'王老师'};load()}
const gradeType:any={S:'danger',A:'warning',B:'primary',C:'info',UNRATED:'info'}
</script><template><section class="page">
<PageHeader eyebrow="CUSTOMER MASTER DATA" title="客户列表" description="以唯一客户编码管理身份、孩子、负责人、等级与客户关系历史。"><el-button>撞单管理</el-button><el-button type="primary" @click="dialog=true">新建客户</el-button></PageHeader>
<div class="surface table-shell"><div class="table-tools"><el-select v-model="grade" placeholder="全部等级" clearable @change="load"><el-option v-for="g in ['S','A','B','C','UNRATED']" :key="g" :label="g==='UNRATED'?'未定级':g+' 级'" :value="g"/></el-select><el-input placeholder="客户编号、姓名或身份"/><span>共 {{rows.length}} 位客户</span></div>
<StatePanel :loading="loading" :error="error" :empty="!rows.length" @retry="load"><el-table :data="rows"><el-table-column prop="customer_no" label="客户编号" width="180"/><el-table-column prop="name" label="客户称呼"/><el-table-column prop="mobile" label="手机号"><template #default="{row}">{{row.mobile?.replace(/(\d{3})\d{4}(\d{4})/,'$1****$2')}}</template></el-table-column><el-table-column prop="grade" label="等级"><template #default="{row}"><el-tag :type="gradeType[row.grade]">{{row.grade==='UNRATED'?'未定级':row.grade}}</el-tag></template></el-table-column><el-table-column prop="owner_name" label="负责人"/><el-table-column prop="status" label="客户状态"/><el-table-column label="操作"><template #default><el-button link type="primary">客户档案</el-button><el-button link>登记跟进</el-button></template></el-table-column></el-table></StatePanel></div>
<el-dialog v-model="dialog" title="新建唯一客户" width="520px"><el-alert title="手机号或 UnionID 任一有效即可创建；分别命中不同客户时进入撞单。" type="info" :closable="false"/><el-form label-position="top" style="margin-top:16px"><el-form-item label="客户称呼" required><el-input v-model="form.name"/></el-form-item><el-form-item label="手机号"><el-input v-model="form.mobile"/></el-form-item><el-form-item label="UnionID"><el-input v-model="form.unionId"/></el-form-item><el-form-item label="负责人"><el-input v-model="form.ownerName"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="create">创建客户</el-button></template></el-dialog>
</section></template>
