<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import '../styles/system-global-config.css'

type DictItem={id:number;label:string;value:string;sort:number;color:string;status:string;description:string}
type DictType={id:number;name:string;code:string;status:string;description:string;items:DictItem[]}
const storageKey='heshu_boss_dictionaries_v1'
const seed:DictType[]=[
  {id:1,name:'线索标记',code:'lead_mark',status:'ACTIVE',description:'线索有效性及重复标记。',items:[{id:101,label:'有效线索',value:'VALID',sort:1,color:'green',status:'ACTIVE',description:''},{id:102,label:'无效线索',value:'INVALID',sort:2,color:'gray',status:'ACTIVE',description:''},{id:103,label:'重复线索',value:'DUPLICATE',sort:3,color:'orange',status:'ACTIVE',description:''}]},
  {id:2,name:'客户等级',code:'customer_grade',status:'ACTIVE',description:'客户S/A/B/C等级展示字典。',items:[{id:201,label:'S级',value:'S',sort:1,color:'red',status:'ACTIVE',description:'重点客户'},{id:202,label:'A级',value:'A',sort:2,color:'orange',status:'ACTIVE',description:''},{id:203,label:'B级',value:'B',sort:3,color:'blue',status:'ACTIVE',description:''},{id:204,label:'C级',value:'C',sort:4,color:'gray',status:'ACTIVE',description:''}]},
  {id:3,name:'线索添加方式',code:'lead_entry_method',status:'ACTIVE',description:'线索进入合数BOSS的方式。',items:[{id:301,label:'渠道同步',value:'CHANNEL',sort:1,color:'blue',status:'ACTIVE',description:''},{id:302,label:'批量导入',value:'IMPORT',sort:2,color:'cyan',status:'ACTIVE',description:''},{id:303,label:'合作方推送',value:'PARTNER_PUSH',sort:3,color:'purple',status:'ACTIVE',description:''},{id:304,label:'转介绍',value:'REFERRAL',sort:4,color:'green',status:'ACTIVE',description:''}]},
  {id:4,name:'平台类型',code:'platform_type',status:'ACTIVE',description:'店铺、渠道和商品的平台来源。',items:[{id:401,label:'抖音',value:'DOUYIN',sort:1,color:'blue',status:'ACTIVE',description:''},{id:402,label:'有赞',value:'YOUZAN',sort:2,color:'green',status:'ACTIVE',description:''},{id:403,label:'小鹅通',value:'XIAOETONG',sort:3,color:'purple',status:'ACTIVE',description:''},{id:404,label:'小红书',value:'XIAOHONGSHU',sort:4,color:'red',status:'ACTIVE',description:''}]}
]
function load(){try{return JSON.parse(localStorage.getItem(storageKey)||'null')||seed}catch{return seed}}
const dictionaries=ref<DictType[]>(load()),typeKeyword=ref(''),itemKeyword=ref(''),selectedId=ref(dictionaries.value[0]?.id),typeDialog=ref(false),itemDialog=ref(false),typeEditing=ref<DictType|null>(null),itemEditing=ref<DictItem|null>(null)
const typeForm=reactive<any>({name:'',code:'',status:'ACTIVE',description:''}),itemForm=reactive<any>({label:'',value:'',sort:1,color:'blue',status:'ACTIVE',description:''})
const selected=computed(()=>dictionaries.value.find(item=>item.id===selectedId.value)||dictionaries.value[0])
const visibleTypes=computed(()=>dictionaries.value.filter(item=>!typeKeyword.value||`${item.name}${item.code}`.toLowerCase().includes(typeKeyword.value.toLowerCase())))
const visibleItems=computed(()=>(selected.value?.items||[]).filter(item=>!itemKeyword.value||`${item.label}${item.value}`.toLowerCase().includes(itemKeyword.value.toLowerCase())).sort((a,b)=>a.sort-b.sort))
function persist(){localStorage.setItem(storageKey,JSON.stringify(dictionaries.value))}
function openType(row?:DictType){typeEditing.value=row||null;Object.assign(typeForm,row||{name:'',code:'',status:'ACTIVE',description:''});typeDialog.value=true}
function saveType(){if(!typeForm.name?.trim()||!typeForm.code?.trim()){ElMessage.warning('请填写字典名称和字典编码');return}if(!typeEditing.value&&!/^[a-z][a-z0-9_]{2,63}$/.test(typeForm.code)){ElMessage.warning('字典编码仅支持小写字母、数字和下划线');return}if(!typeEditing.value&&dictionaries.value.some(item=>item.code===typeForm.code)){ElMessage.warning('字典编码已存在');return}if(typeEditing.value)Object.assign(typeEditing.value,{...typeForm,code:typeEditing.value.code});else{const row={...typeForm,id:Date.now(),items:[]};dictionaries.value.unshift(row);selectedId.value=row.id}persist();typeDialog.value=false;ElMessage.success(typeEditing.value?'字典已更新':'字典已创建')}
function openItem(row?:DictItem){itemEditing.value=row||null;Object.assign(itemForm,row||{label:'',value:'',sort:(selected.value?.items.length||0)+1,color:'blue',status:'ACTIVE',description:''});itemDialog.value=true}
function saveItem(){if(!itemForm.label?.trim()||!itemForm.value?.trim()){ElMessage.warning('请填写字典项标签和值');return}if(!itemEditing.value&&selected.value.items.some(item=>item.value===itemForm.value)){ElMessage.warning('当前字典下的字典项值已存在');return}if(itemEditing.value)Object.assign(itemEditing.value,itemForm);else selected.value.items.push({...itemForm,id:Date.now()});persist();itemDialog.value=false;ElMessage.success(itemEditing.value?'字典项已更新':'字典项已新增')}
async function toggleType(row:DictType){await ElMessageBox.confirm(`${row.status==='ACTIVE'?'停用':'启用'}字典“${row.name}”？停用后业务页面不可继续选择，但历史数据仍按原值展示。`,'确认状态变更',{type:'warning'});row.status=row.status==='ACTIVE'?'INACTIVE':'ACTIVE';persist();ElMessage.success('字典状态已更新')}
async function toggleItem(row:DictItem){await ElMessageBox.confirm(`${row.status==='ACTIVE'?'停用':'启用'}字典项“${row.label}”？`,'确认状态变更',{type:'warning'});row.status=row.status==='ACTIVE'?'INACTIVE':'ACTIVE';persist();ElMessage.success('字典项状态已更新')}
const colorMap:any={blue:'primary',green:'success',orange:'warning',red:'danger',gray:'info',cyan:'success',purple:''}
</script>

<template>
  <section class="page global-config-page dictionary-page">
    <PageHeader eyebrow="SYSTEM GOVERNANCE · BUSINESS DICTIONARY" title="字典管理" description="统一维护业务枚举及显示口径；停用旧值不影响历史数据，新增值经授权后供业务模块选择。"><el-button type="primary" @click="openType()">新增字典</el-button></PageHeader>
    <div class="dictionary-guide surface"><b>字典治理边界</b><span>固定、可枚举的业务选项放入字典</span><i></i><span>影响业务计算的阈值放入系统参数</span><i></i><span>复杂条件与动作放入规则中心</span></div>
    <div class="dictionary-shell">
      <aside class="surface dictionary-types"><div class="dictionary-side-head"><div><b>字典类型</b><span>{{ dictionaries.length }} 个</span></div><el-button link type="primary" @click="openType()">新增</el-button></div><el-input v-model="typeKeyword" clearable prefix-icon="Search" placeholder="搜索名称或编码"/><div class="dictionary-type-list"><button v-for="item in visibleTypes" :key="item.id" :class="{active:selected?.id===item.id}" @click="selectedId=item.id"><span><b>{{ item.name }}</b><code>{{ item.code }}</code></span><em>{{ item.items.length }}</em><i :class="{off:item.status!=='ACTIVE'}"></i></button><el-empty v-if="!visibleTypes.length" description="未找到字典" :image-size="64"/></div></aside>
      <main class="surface dictionary-items"><div class="dictionary-context"><div><span>当前字典</span><h2>{{ selected?.name }}</h2><code>{{ selected?.code }}</code><p>{{ selected?.description||'暂无说明' }}</p></div><div><el-tag :type="selected?.status==='ACTIVE'?'success':'info'">{{ selected?.status==='ACTIVE'?'启用':'停用' }}</el-tag><el-button @click="openType(selected)">编辑字典</el-button><el-button :type="selected?.status==='ACTIVE'?'danger':'success'" plain @click="toggleType(selected)">{{ selected?.status==='ACTIVE'?'停用':'启用' }}</el-button></div></div><div class="dictionary-toolbar"><el-input v-model="itemKeyword" clearable prefix-icon="Search" placeholder="搜索字典项标签或值"/><el-button type="primary" :disabled="selected?.status!=='ACTIVE'" @click="openItem()">新增字典项</el-button></div><el-table :data="visibleItems" row-key="id"><el-table-column prop="label" label="字典项标签" min-width="170"><template #default="{row}"><b class="primary-cell">{{ row.label }}</b><small>{{ row.description||'—' }}</small></template></el-table-column><el-table-column prop="value" label="字典项值" min-width="150"><template #default="{row}"><code>{{ row.value }}</code></template></el-table-column><el-table-column prop="sort" label="排序" width="82" align="center"/><el-table-column label="显示效果" width="120"><template #default="{row}"><el-tag :type="colorMap[row.color]" effect="light">{{ row.label }}</el-tag></template></el-table-column><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{ row.status==='ACTIVE'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="160" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openItem(row)">编辑</el-button><el-button link :type="row.status==='ACTIVE'?'danger':'success'" @click="toggleItem(row)">{{ row.status==='ACTIVE'?'停用':'启用' }}</el-button></template></el-table-column></el-table><div class="global-pagination"><span>共 {{ visibleItems.length }} 条</span><el-pagination background layout="prev,pager,next,sizes" :total="visibleItems.length" :page-size="10"/></div></main>
    </div>
    <el-dialog v-model="typeDialog" :title="typeEditing?'编辑字典':'新增字典'" width="620px"><el-form label-position="top" class="global-form"><el-form-item label="字典名称" required><el-input v-model="typeForm.name" maxlength="40" placeholder="例如：客户等级"/></el-form-item><el-form-item label="字典编码" required><el-input v-model="typeForm.code" :disabled="!!typeEditing" placeholder="customer_grade"/><small>保存后不可修改；业务接口通过编码读取字典。</small></el-form-item><el-form-item label="状态"><el-radio-group v-model="typeForm.status"><el-radio value="ACTIVE">启用</el-radio><el-radio value="INACTIVE">停用</el-radio></el-radio-group></el-form-item><el-form-item label="说明"><el-input v-model="typeForm.description" type="textarea" :rows="3" maxlength="160" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="typeDialog=false">取消</el-button><el-button type="primary" @click="saveType">保存字典</el-button></template></el-dialog>
    <el-dialog v-model="itemDialog" :title="itemEditing?'编辑字典项':'新增字典项'" width="660px"><el-alert :title="`所属字典：${selected?.name}（${selected?.code}）`" type="info" :closable="false"/><el-form label-position="top" class="global-form"><div class="form-grid"><el-form-item label="字典项标签" required><el-input v-model="itemForm.label" maxlength="40" placeholder="业务页面展示文本"/></el-form-item><el-form-item label="字典项值" required><el-input v-model="itemForm.value" :disabled="!!itemEditing" maxlength="64" placeholder="接口和数据库保存值"/></el-form-item><el-form-item label="排序"><el-input-number v-model="itemForm.sort" :min="0" :max="999" style="width:100%"/></el-form-item><el-form-item label="标签颜色"><el-select v-model="itemForm.color" style="width:100%"><el-option label="蓝色" value="blue"/><el-option label="绿色" value="green"/><el-option label="橙色" value="orange"/><el-option label="红色" value="red"/><el-option label="灰色" value="gray"/><el-option label="青色" value="cyan"/><el-option label="紫色" value="purple"/></el-select></el-form-item><el-form-item label="状态"><el-radio-group v-model="itemForm.status"><el-radio value="ACTIVE">启用</el-radio><el-radio value="INACTIVE">停用</el-radio></el-radio-group></el-form-item></div><el-form-item label="说明"><el-input v-model="itemForm.description" type="textarea" :rows="2" maxlength="120"/></el-form-item></el-form><template #footer><el-button @click="itemDialog=false">取消</el-button><el-button type="primary" @click="saveItem">保存字典项</el-button></template></el-dialog>
  </section>
</template>
