<script setup lang="ts">
// @ts-nocheck
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import http from '../api/http'
import PageHeader from '../components/PageHeader.vue'
import StatePanel from '../components/StatePanel.vue'

const employees=ref<any[]>([]), organizations=ref<any[]>([]), loading=ref(false), error=ref(''), keyword=ref(''), status=ref(''), drawer=ref(false), current=ref<any>(null), saving=ref(false), syncDialog=ref(false), syncMode=ref<'BASELINE'|'PUSH'|'RECONCILE'>('PUSH'), syncRunning=ref(false), provisionDialog=ref(false), provisionEmployeeId=ref<number|null>(null), provisionRunning=ref(false), bossMasterEnabled=ref(true)
const roles=[{label:'运营',value:'OPERATION'},{label:'客服',value:'CUSTOMER_SERVICE'},{label:'规划师',value:'PLANNER'},{label:'一转老师',value:'FIRST_CONVERSION'},{label:'课程顾问',value:'COURSE_ADVISOR'},{label:'财务专员',value:'FINANCE'},{label:'系统管理员',value:'SYSTEM_ADMIN'}]
const positions=[{label:'本人数据岗',scope:'本人负责、创建或被明确协作的数据'},{label:'小组管理岗',scope:'所负责小组及组内员工数据'},{label:'部门管理岗',scope:'所负责部门及全部下级小组数据'},{label:'跨部门管理岗',scope:'明确指定的多个部门或小组数据'},{label:'公司数据管理岗',scope:'当前公司全部业务数据'}]
const form=reactive<any>({name:'',legal_name:'',mobile:'',email:'',organization_id:null,position_name:'本人数据岗',role_codes:['COURSE_ADVISOR'],account_status:'ACTIVE',create_login:true})
const visible=computed(()=>{const term=keyword.value.trim().toLowerCase();return employees.value.filter(row=>(!status.value||row.account_status===status.value)&&(!term||`${row.employee_no}${row.name}${row.legal_name||''}${row.mobile_masked}${row.email||''}${row.position_name||''}`.toLowerCase().includes(term)))})
const orgName=(id:number)=>organizations.value.find(item=>item.id===id)?.name||'未归属'
const scopeText=(name:string)=>positions.find(item=>item.label===name)?.scope||'未配置数据岗位'
const roleNames=(row:any)=>row.role_names?.length?row.role_names:(row.role_codes||[]).map((code:string)=>roles.find(item=>item.value===code)?.label||code)
const provisionCandidates=computed(()=>employees.value.filter(row=>row.account_status==='ACTIVE'&&!row.wecom_user_id))
const provisionEmployee=computed(()=>employees.value.find(row=>row.id===provisionEmployeeId.value))
const proposedWecomUserId=computed(()=>provisionEmployee.value?`boss_${String(provisionEmployee.value.employee_no||provisionEmployee.value.id).toLowerCase()}`:'')
async function load(){loading.value=true;error.value='';try{const [employeeResult,organizationResult]:any=await Promise.all([http.get('/system/employees'),http.get('/system/organizations')]);employees.value=employeeResult.data;organizations.value=organizationResult.data}catch(e:any){error.value=e.message}finally{loading.value=false}}
function openCreate(){current.value=null;Object.assign(form,{name:'',legal_name:'',mobile:'',email:'',organization_id:null,position_name:'本人数据岗',role_codes:['COURSE_ADVISOR'],account_status:'ACTIVE',create_login:true});drawer.value=true}
function openDetail(row:any){current.value=row;Object.assign(form,{...row,role_codes:row.role_codes?.length?row.role_codes:['COURSE_ADVISOR'],position_name:positions.some(item=>item.label===row.position_name)?row.position_name:'本人数据岗'});drawer.value=true}
async function save(){if(!form.name||!form.mobile||!form.organization_id||!form.position_name||!form.role_codes.length){ElMessage.warning('请完整填写员工、组织、业务角色和数据岗位');return}saving.value=true;try{if(current.value){Object.assign(current.value,form);ElMessage.success('员工权限关系已更新')}else{await http.post('/system/employees',form);await load();ElMessage.success('员工已新增')}drawer.value=false}catch(e:any){ElMessage.error(e.message||'保存失败')}finally{saving.value=false}}
const syncCopy=computed(()=>({
  BASELINE:{title:'企微基线导入',description:'只读取整改后的企微组织和成员至暂存区，完成差异确认后再建立合数BOSS正式员工档案；飞书数据不导入、不比对。',confirm:'创建基线导入任务'},
  PUSH:{title:'同步至企业微信',description:'将合数BOSS中已确认的员工、组织和在职状态增量下发企业微信；企微不会反向覆盖员工编号和主数据。',confirm:'创建企微同步任务'},
  RECONCILE:{title:'企微差异对账',description:'只对比合数BOSS与企业微信的组织、成员及状态差异，生成异常清单；飞书不参与对账，也不自动删除或静默覆盖。',confirm:'创建差异对账任务'}
})[syncMode.value])
function openSync(mode:'BASELINE'|'PUSH'|'RECONCILE'){syncMode.value=mode;syncDialog.value=true}
async function runSync(){syncRunning.value=true;await new Promise(resolve=>setTimeout(resolve,420));syncRunning.value=false;syncDialog.value=false;ElMessage.success(`${syncCopy.value.title}任务已创建，可在异常中心查看执行结果`)}
function openProvision(row?:any){if(!bossMasterEnabled.value){ElMessage.warning('自有系统主控已关闭，请先在企业微信创建成员并同步至合数BOSS');return}provisionEmployeeId.value=row?.id||null;provisionDialog.value=true}
async function provisionWecom(){const row=provisionEmployee.value;if(!row){ElMessage.warning('请选择需要开通企微的员工');return}if(!row.mobile_masked&&!row.mobile){ElMessage.warning('员工手机号缺失，无法执行企微成员查重与邀请');return}if(row.wecom_user_id){ElMessage.warning('该员工已绑定企微身份，请勿重复创建');return}provisionRunning.value=true;await new Promise(resolve=>setTimeout(resolve,620));row.wecom_user_id=proposedWecomUserId.value;row.wecom_provision_status='PENDING_ACTIVATION';provisionRunning.value=false;provisionDialog.value=false;ElMessage.success('企微成员已创建并发送邀请，当前状态：待员工激活')}
onMounted(load)
</script>

<template><section class="page employee-page"><PageHeader eyebrow="HESHU BOSS · EMPLOYEE ACCESS" title="员工管理" description="初始组织员工基线全部来自整改后的企业微信；验收后由合数BOSS统一维护并向企业微信同步。"><el-button @click="openSync('PUSH')">同步至企微</el-button><el-dropdown trigger="click"><el-button>导入与对账<span class="el-icon--right">⌄</span></el-button><template #dropdown><el-dropdown-menu><el-dropdown-item @click="openSync('BASELINE')">企微基线导入</el-dropdown-item><el-dropdown-item @click="openSync('RECONCILE')">企微差异对账</el-dropdown-item></el-dropdown-menu></template></el-dropdown><el-button type="primary" @click="openCreate">新增员工</el-button></PageHeader>
  <div class="master-flow" aria-label="组织员工数据主责关系"><div class="master-node primary"><small>正式主写源</small><b>合数BOSS</b><span>员工编号 · 主组织 · 在职状态 · 权限</span></div><i>初始化读取 / 正式下发 ⇄</i><div class="master-node"><small>唯一初始基线来源</small><b>企业微信</b><span>CorpID + UserID · 组织通讯录 · 接待状态</span></div></div>
  <el-alert class="identity-rule-alert" title="飞书不参与员工初始化、身份匹配或同步对账；一个企微身份只能绑定一个合数BOSS账号，一个账号也只能保留一个生效企微身份。换绑必须先解绑并保留历史记录。" type="info" :closable="false" show-icon/>
  <div class="wecom-provision-bar"><div><b>企微成员开通</b><span>先按手机号查询企微成员；已存在则校验绑定，不存在则创建成员并发送邀请。创建成功不等于已激活。</span></div><el-tag :type="bossMasterEnabled?'success':'info'">自有系统主控{{ bossMasterEnabled?'已开启':'已关闭' }}</el-tag><el-button type="primary" :disabled="!bossMasterEnabled" @click="openProvision()">创建企微成员</el-button></div>
  <div class="access-rule"><div><span>①</span><b>主组织</b><small>确定员工归属</small></div><i>＋</i><div><span>②</span><b>业务角色</b><small>运营 / 客服 / 规划师</small></div><i>＋</i><div><span>③</span><b>数据岗位</b><small>本人 / 小组 / 部门 / 公司</small></div><i>＝</i><div class="result"><span>✓</span><b>员工有效权限</b><small>功能权限与数据范围共同生效</small></div></div>
  <main class="surface employee-shell"><div class="employee-toolbar"><div><el-input v-model="keyword" clearable prefix-icon="Search" placeholder="搜索员工编号、姓名、手机号或岗位"/><el-select v-model="status" clearable placeholder="账号状态"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></div><span>共 {{ visible.length }} 名员工</span></div><StatePanel :loading="loading" :error="error" @retry="load"><el-table :data="visible" row-key="id"><el-table-column prop="employee_no" label="员工编号" width="118"/><el-table-column prop="name" label="员工名称" min-width="120"><template #default="{row}"><button class="employee-link" @click="openDetail(row)">{{ row.name }}</button><small>{{ row.legal_name||row.name }}</small></template></el-table-column><el-table-column label="主组织" min-width="150"><template #default="{row}">{{ orgName(row.organization_id) }}</template></el-table-column><el-table-column label="业务角色" min-width="180"><template #default="{row}"><el-tag v-for="item in roleNames(row)" :key="item" size="small" class="role-tag">{{ item }}</el-tag><span v-if="!roleNames(row).length">未配置</span></template></el-table-column><el-table-column label="数据岗位" min-width="220"><template #default="{row}"><b>{{ positions.some(item=>item.label===row.position_name)?row.position_name:'本人数据岗' }}</b><small class="scope-copy">{{ scopeText(positions.some(item=>item.label===row.position_name)?row.position_name:'本人数据岗') }}</small></template></el-table-column><el-table-column prop="mobile_masked" label="手机号" width="135"/><el-table-column label="企微状态" width="110"><template #default="{row}"><el-tag v-if="row.wecom_provision_status==='PENDING_ACTIVATION'" type="warning">待激活</el-tag><el-tag v-else-if="row.wecom_user_id" type="success">已绑定</el-tag><el-tag v-else type="info">未开通</el-tag></template></el-table-column><el-table-column prop="account_status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.account_status==='ACTIVE'?'success':'info'">{{ row.account_status==='ACTIVE'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="210" fixed="right"><template #default="{row}"><el-button v-if="!row.wecom_user_id&&row.account_status==='ACTIVE'" link type="primary" @click="openProvision(row)">开通企微</el-button><el-button link type="primary" @click="openDetail(row)">详情 / 编辑</el-button></template></el-table-column></el-table></StatePanel></main>
  <el-drawer v-model="drawer" :title="current?'员工详情与权限':'新增员工'" size="620px"><el-alert title="业务角色可多选且功能权限取并集；一个员工默认绑定一个数据岗位，角色不会扩大数据范围。" type="info" :closable="false" show-icon/><el-form label-position="top" class="employee-form"><div class="form-grid"><el-form-item label="员工名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="真实姓名" required><el-input v-model="form.legal_name"/></el-form-item><el-form-item label="手机号" required><el-input v-model="form.mobile"/></el-form-item><el-form-item label="邮箱"><el-input v-model="form.email"/></el-form-item><el-form-item label="主组织" required><el-select v-model="form.organization_id" filterable style="width:100%"><el-option v-for="item in organizations.filter(row=>['DEPARTMENT','GROUP_TEAM'].includes(row.type)&&row.status==='ACTIVE')" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="数据岗位" required><el-select v-model="form.position_name" style="width:100%"><el-option v-for="item in positions" :key="item.label" :label="item.label" :value="item.label"/></el-select><small class="field-help">{{ scopeText(form.position_name) }}</small></el-form-item></div><el-form-item label="业务角色" required><el-select v-model="form.role_codes" multiple style="width:100%" placeholder="如运营、客服、规划师"><el-option v-for="item in roles" :key="item.value" :label="item.label" :value="item.value"/></el-select><small class="field-help">角色负责菜单、操作和敏感字段权限，不配置数据范围。</small></el-form-item><el-form-item label="账号状态"><el-radio-group v-model="form.account_status"><el-radio value="ACTIVE">启用</el-radio><el-radio value="INACTIVE">停用</el-radio></el-radio-group></el-form-item></el-form><div class="drawer-actions"><el-button @click="drawer=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存员工</el-button></div></el-drawer>
  <el-dialog v-model="syncDialog" :title="syncCopy.title" width="560px"><div class="sync-dialog-copy"><span>企微</span><p>{{ syncCopy.description }}</p></div><template #footer><el-button @click="syncDialog=false">取消</el-button><el-button type="primary" :loading="syncRunning" @click="runSync">{{ syncCopy.confirm }}</el-button></template></el-dialog>
  <el-dialog v-model="provisionDialog" title="创建并邀请企微成员" width="680px"><el-alert title="系统将先按手机号查询企微通讯录，避免重复创建；创建成功后员工仍需完成企微激活。" type="info" :closable="false" show-icon/><div class="provision-steps"><span class="active">1 校验员工档案</span><span>2 查询或创建成员</span><span>3 发送邀请</span><span>4 等待激活</span></div><el-form label-position="top"><el-form-item label="选择员工" required><el-select v-model="provisionEmployeeId" filterable placeholder="输入员工名称或员工编号" style="width:100%"><el-option v-for="item in provisionCandidates" :key="item.id" :label="`${item.name} · ${item.employee_no} · ${orgName(item.organization_id)}`" :value="item.id"/></el-select></el-form-item><div v-if="provisionEmployee" class="provision-preview"><div><small>员工手机号</small><b>{{ provisionEmployee.mobile_masked||provisionEmployee.mobile }}</b></div><div><small>映射企微部门</small><b>{{ orgName(provisionEmployee.organization_id) }}</b></div><div><small>拟生成企微 UserID</small><b>{{ proposedWecomUserId }}</b></div><div><small>绑定规则</small><b>一个账号 ↔ 一个企微身份</b></div></div><el-alert v-if="provisionEmployee" title="若手机号已对应现有企微成员，系统不会重复创建，将在唯一性校验通过后绑定；若已绑定其他BOSS账号，则进入身份冲突队列。" type="warning" :closable="false"/></el-form><template #footer><el-button @click="provisionDialog=false">取消</el-button><el-button type="primary" :loading="provisionRunning" @click="provisionWecom">创建并发送邀请</el-button></template></el-dialog>
</section></template>

<style scoped>
.master-flow{display:grid;grid-template-columns:1.2fr auto 1fr;align-items:center;gap:12px;margin-bottom:16px;padding:14px;background:#f8fbff;border:1px solid #dce8f8;border-radius:14px}
.master-node{display:grid;gap:3px;padding:12px 14px;background:#fff;border:1px solid #dce6f3;border-radius:11px}
.master-node.primary{border-color:#74a9f1;box-shadow:inset 3px 0 #2e78e8}
.master-node small{color:#8193aa}.master-node b{color:#172842;font-size:16px}.master-node span{color:#6f829b;font-size:12px}
.master-flow i{font-style:normal;color:#2e78e8;font-size:12px;font-weight:700}
.identity-rule-alert{margin:-4px 0 16px}
.wecom-provision-bar{display:flex;align-items:center;gap:14px;margin:0 0 16px;padding:14px 16px;border:1px solid #dce8f8;border-radius:14px;background:#fff}.wecom-provision-bar>div{display:grid;gap:3px;flex:1}.wecom-provision-bar b{color:#172842}.wecom-provision-bar span{color:#6f829b;font-size:13px}
.provision-steps{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin:18px 0}.provision-steps span{padding:10px;border-radius:9px;background:#f2f5f9;color:#7a8ca4;text-align:center;font-size:12px}.provision-steps span.active{background:#eaf3ff;color:#176ee8;font-weight:800}.provision-preview{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0 0 14px}.provision-preview>div{display:grid;gap:4px;padding:12px;border:1px solid #e2eaf5;border-radius:10px}.provision-preview small{color:#8293aa}.provision-preview b{color:#223651}
.sync-dialog-copy{display:flex;gap:12px;align-items:flex-start;margin-bottom:14px}.sync-dialog-copy>span{flex:0 0 auto;padding:5px 9px;border-radius:7px;background:#eaf3ff;color:#176ee8;font-size:12px;font-weight:800}.sync-dialog-copy p{margin:2px 0 0;color:#526882;line-height:1.7}
@media(max-width:900px){.master-flow{grid-template-columns:1fr}.master-flow i{text-align:center}.wecom-provision-bar{align-items:flex-start;flex-direction:column}.provision-preview{grid-template-columns:1fr}}
</style>

<style scoped>.employee-page{--ink:#172842}.access-rule{display:grid;grid-template-columns:1fr auto 1fr auto 1fr auto 1.25fr;align-items:center;gap:12px;margin-bottom:20px}.access-rule>div{background:#fff;border:1px solid #dce6f3;border-radius:14px;padding:16px;display:grid;grid-template-columns:auto 1fr;column-gap:10px;box-shadow:0 8px 24px rgba(37,70,115,.05)}.access-rule>div.result{border-color:#7eaeef;background:linear-gradient(135deg,#edf5ff,#fff)}.access-rule span{grid-row:1/3;color:#2e78e8;font-weight:800}.access-rule b{color:var(--ink)}.access-rule small{color:#8193aa}.access-rule i{font-style:normal;color:#79a5df;font-size:20px}.employee-shell{overflow:hidden}.employee-toolbar{display:flex;justify-content:space-between;align-items:center;padding:18px 20px;border-bottom:1px solid #e8eef6;color:#8192a8}.employee-toolbar>div{display:flex;gap:12px}.employee-toolbar .el-input{width:340px}.employee-toolbar .el-select{width:150px}.employee-link{display:block;border:0;background:none;color:#176ee8;font-weight:700;cursor:pointer;padding:0}.employee-link+small,.scope-copy{display:block;color:#8da0b8;margin-top:4px}.role-tag{margin:2px 4px 2px 0}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}.field-help{display:block;margin-top:6px;color:#8193aa}.drawer-actions{display:flex;justify-content:flex-end;margin-top:24px}@media(max-width:900px){.access-rule{grid-template-columns:1fr}.access-rule i{text-align:center}.employee-toolbar{align-items:flex-start}.employee-toolbar>div{flex-direction:column}.employee-toolbar .el-input,.employee-toolbar .el-select{width:100%}.form-grid{grid-template-columns:1fr}}</style>
