<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'

type Opportunity={id:number;no:string;customer:string;name:string;course:string;amount:number;owner:string;stage:string;status:string;expectedDate:string;leadNo:string;latestFollow:string}
const storageKey='heshu_boss_opportunities_v1'
const seed:Opportunity[]=[
  {id:1,no:'OP202608250001',customer:'钱女士',name:'家庭学习力提升',course:'2980成长训练营',amount:2980,owner:'陈老师',stage:'需求确认',status:'进行中',expectedDate:'2026-08-30',leadNo:'L202608160003',latestFollow:'已确认孩子学习习惯问题，待预约试听'},
  {id:2,no:'OP202608250002',customer:'吴女士',name:'家庭教育进阶服务',course:'1V1家庭诊断',amount:12800,owner:'王老师',stage:'待成交',status:'进行中',expectedDate:'2026-09-03',leadNo:'L202608150008',latestFollow:'已完成2980课程，等待规划师方案'},
  {id:3,no:'OP202608210008',customer:'周女士',name:'暑期体验营转化',course:'2980成长训练营',amount:2980,owner:'王老师',stage:'挖需中',status:'进行中',expectedDate:'2026-09-08',leadNo:'L202608160001',latestFollow:'客户已加微，需求信息待补充'}]
function load(){try{return JSON.parse(localStorage.getItem(storageKey)||'null')||seed}catch{return seed}}
const rows=ref<Opportunity[]>(load()),keyword=ref(''),stage=ref(''),status=ref(''),dialog=ref(false),detail=ref(false),editing=ref<Opportunity|null>(null),active=ref<Opportunity|null>(null)
const form=reactive<any>({customer:'',name:'',course:'',amount:2980,owner:'王老师',stage:'未挖需',status:'进行中',expectedDate:'',leadNo:'',latestFollow:''})
const visible=computed(()=>rows.value.filter(row=>(!keyword.value||`${row.no}${row.customer}${row.name}${row.course}`.includes(keyword.value))&&(!stage.value||row.stage===stage.value)&&(!status.value||row.status===status.value)))
const stats=computed(()=>({all:rows.value.length,active:rows.value.filter(row=>row.status==='进行中').length,win:rows.value.filter(row=>row.stage==='赢单').length,amount:rows.value.filter(row=>row.status==='进行中').reduce((sum,row)=>sum+row.amount,0)}))
function persist(){localStorage.setItem(storageKey,JSON.stringify(rows.value))}
function openForm(row?:Opportunity){editing.value=row||null;Object.assign(form,row||{customer:'',name:'',course:'',amount:2980,owner:'王老师',stage:'未挖需',status:'进行中',expectedDate:'',leadNo:'',latestFollow:''});dialog.value=true}
function save(){if(!form.customer||!form.name)return ElMessage.warning('请填写客户和商机名称');if(editing.value)Object.assign(editing.value,form);else rows.value.unshift({...form,id:Date.now(),no:`OP${new Date().toISOString().replace(/\D/g,'').slice(0,14)}`});persist();dialog.value=false;ElMessage.success(editing.value?'商机已更新':'商机已创建')}
function show(row:Opportunity){active.value=row;detail.value=true}
</script>

<template>
  <section class="page opportunity-page">
    <PageHeader eyebrow="OPPORTUNITY PIPELINE" title="商机管理" description="商机阶段独立于客户生命周期，记录明确购买意向、预计金额、负责人和下一步动作。"><el-button type="primary" @click="openForm()">新建商机</el-button></PageHeader>
    <div class="opportunity-stats"><div><span>全部商机</span><b>{{ stats.all }}</b></div><div><span>进行中</span><b>{{ stats.active }}</b></div><div><span>已赢单</span><b>{{ stats.win }}</b></div><div><span>预计金额</span><b>¥{{ stats.amount.toLocaleString() }}</b></div></div>
    <div class="surface opportunity-table"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="商机编号、客户、名称或课程"/><el-select v-model="stage" clearable placeholder="商机阶段"><el-option v-for="item in ['未挖需','挖需中','需求确认','待成交','赢单','输单']" :key="item" :label="item" :value="item"/></el-select><el-select v-model="status" clearable placeholder="状态"><el-option label="进行中" value="进行中"/><el-option label="已关闭" value="已关闭"/></el-select><el-button type="primary">查询</el-button><span>共 {{ visible.length }} 条</span></div><el-table :data="visible"><el-table-column prop="no" label="商机编号" width="180"/><el-table-column label="客户 / 商机" min-width="220"><template #default="{row}"><b>{{ row.customer }} · {{ row.name }}</b><small>{{ row.course }}</small></template></el-table-column><el-table-column prop="amount" label="预计金额" width="120"><template #default="{row}">¥{{ row.amount.toLocaleString() }}</template></el-table-column><el-table-column prop="owner" label="负责人" width="110"/><el-table-column prop="stage" label="阶段" width="110"><template #default="{row}"><el-tag effect="plain">{{ row.stage }}</el-tag></template></el-table-column><el-table-column prop="expectedDate" label="预计成交" width="120"/><el-table-column prop="latestFollow" label="最近进展" min-width="220" show-overflow-tooltip/><el-table-column label="操作" width="130" fixed="right"><template #default="{row}"><el-button link type="primary" @click="show(row)">详情</el-button><el-button link type="primary" @click="openForm(row)">编辑</el-button></template></el-table-column></el-table></div>
    <el-dialog v-model="dialog" :title="editing?'编辑商机':'新建商机'" width="680px"><el-form label-position="top"><div class="form-grid"><el-form-item label="客户" required><el-input v-model="form.customer"/></el-form-item><el-form-item label="来源线索"><el-input v-model="form.leadNo"/></el-form-item><el-form-item label="商机名称" required><el-input v-model="form.name"/></el-form-item><el-form-item label="意向课程"><el-input v-model="form.course"/></el-form-item><el-form-item label="预计金额"><el-input-number v-model="form.amount" :min="0" style="width:100%"/></el-form-item><el-form-item label="负责人"><el-input v-model="form.owner"/></el-form-item><el-form-item label="商机阶段"><el-select v-model="form.stage" style="width:100%"><el-option v-for="item in ['未挖需','挖需中','需求确认','待成交','赢单','输单']" :key="item" :label="item" :value="item"/></el-select></el-form-item><el-form-item label="预计成交日期"><el-date-picker v-model="form.expectedDate" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></div><el-form-item label="最近进展"><el-input v-model="form.latestFollow" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存商机</el-button></template></el-dialog>
    <el-drawer v-model="detail" size="560px"><template #header><div><small>{{ active?.no }}</small><h2>{{ active?.name }}</h2></div></template><div class="detail-grid"><div><span>客户</span><b>{{ active?.customer }}</b></div><div><span>意向课程</span><b>{{ active?.course }}</b></div><div><span>预计金额</span><b>¥{{ active?.amount.toLocaleString() }}</b></div><div><span>负责人</span><b>{{ active?.owner }}</b></div><div><span>当前阶段</span><b>{{ active?.stage }}</b></div><div><span>预计成交</span><b>{{ active?.expectedDate }}</b></div></div><div class="follow-card"><span>最近进展</span><b>{{ active?.latestFollow }}</b><small>来源线索：{{ active?.leadNo||'—' }}</small></div></el-drawer>
  </section>
</template>

<style scoped>
.opportunity-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:14px}.opportunity-stats>div{padding:18px;border:1px solid var(--line);border-radius:14px;background:#fff}.opportunity-stats span{color:var(--muted);font-size:12px}.opportunity-stats b{display:block;margin-top:8px;font-size:25px}.opportunity-table{overflow:hidden}.toolbar{display:flex;align-items:center;gap:10px;padding:16px;border-bottom:1px solid var(--line)}.toolbar .el-input{width:300px}.toolbar .el-select{width:140px}.toolbar span{margin-left:auto;color:var(--muted);font-size:12px}.opportunity-table small{display:block;margin-top:4px;color:var(--muted)}.form-grid,.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.detail-grid>div{padding:14px;border:1px solid var(--line);border-radius:12px}.detail-grid span,.follow-card span,.follow-card small{display:block;color:var(--muted);font-size:12px}.detail-grid b{display:block;margin-top:6px}.follow-card{margin-top:16px;padding:18px;border-left:3px solid var(--primary);background:#f7faff}.follow-card b{display:block;margin:8px 0}@media(max-width:800px){.opportunity-stats{grid-template-columns:1fr 1fr}.toolbar{flex-wrap:wrap}.form-grid,.detail-grid{grid-template-columns:1fr}}
</style>
