<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'

type Scope='SELF'|'GROUP'|'DEPARTMENT'|'CUSTOM'|'COMPANY'
type Position={id:number;code:string;name:string;scope:Scope;organizations:string[];includeChildren:boolean;members:number;status:'ACTIVE'|'INACTIVE';description:string}
const keyword=ref(''), scopeFilter=ref(''), drawer=ref(false), mode=ref<'edit'|'members'|'preview'>('edit'), current=ref<Position|null>(null)
const rows=ref<Position[]>([
  {id:1,code:'POS-SELF-001',name:'本人数据岗',scope:'SELF',organizations:[],includeChildren:false,members:42,status:'ACTIVE',description:'查看本人负责、创建或被明确协作的数据'},
  {id:2,code:'POS-GROUP-001',name:'小组管理岗',scope:'GROUP',organizations:['本部门'],includeChildren:false,members:8,status:'ACTIVE',description:'动态读取员工本部门数据'},
  {id:3,code:'POS-DEPT-001',name:'部门管理岗',scope:'DEPARTMENT',organizations:['本部门及下级部门'],includeChildren:true,members:6,status:'ACTIVE',description:'动态读取员工本部门及下级部门数据'},
  {id:4,code:'POS-CUSTOM-001',name:'跨部门管理岗',scope:'CUSTOM',organizations:['一转事业部','客户运营部'],includeChildren:true,members:3,status:'ACTIVE',description:'查看岗位中明确配置的多个组织范围'},
  {id:5,code:'POS-COMPANY-001',name:'公司数据管理岗',scope:'COMPANY',organizations:['当前公司'],includeChildren:true,members:5,status:'ACTIVE',description:'查看当前公司全部业务数据'}
])
const form=reactive<any>({name:'',code:'保存后自动生成',scope:'SELF',organizations:[],includeChildren:true,status:'ACTIVE',description:''})
const scopeOptions=[{value:'SELF',label:'本人数据'},{value:'GROUP',label:'本部门'},{value:'DEPARTMENT',label:'本部门及下级部门'},{value:'CUSTOM',label:'自定义组织'},{value:'COMPANY',label:'当前公司全部'}]
const scopeLabel=(value:Scope)=>scopeOptions.find(item=>item.value===value)?.label||value
const visibleRows=computed(()=>{const term=keyword.value.trim().toLowerCase();return rows.value.filter(row=>(!scopeFilter.value||row.scope===scopeFilter.value)&&(!term||`${row.code}${row.name}${row.description}`.toLowerCase().includes(term)))})
function open(row?:Position,nextMode:'edit'|'members'|'preview'='edit'){current.value=row||null;mode.value=nextMode;Object.assign(form,row?JSON.parse(JSON.stringify(row)):{name:'',code:'保存后自动生成',scope:'SELF',organizations:[],includeChildren:true,status:'ACTIVE',description:''});drawer.value=true}
function save(){if(!form.name){ElMessage.warning('请输入岗位名称');return}if(form.scope==='CUSTOM'&&!form.organizations.length){ElMessage.warning('自定义范围至少选择一个组织');return}if(current.value)Object.assign(current.value,form);else rows.value.push({...form,id:Date.now(),members:0,code:`POS-${String(rows.value.length+1).padStart(3,'0')}`});drawer.value=false;ElMessage.success('岗位数据范围已保存')}
async function remove(row:Position){if(row.members){await ElMessageBox.alert(`该岗位仍关联 ${row.members} 名员工，请先调整员工岗位。`,'暂时无法删除',{type:'warning'});return}rows.value=rows.value.filter(item=>item.id!==row.id)}
</script>

<template>
  <section class="page position-page">
    <PageHeader eyebrow="HESHU BOSS · DATA SCOPE" title="岗位管理" description="岗位只配置数据可见范围；员工的菜单和操作能力由业务角色决定。"><el-button type="primary" @click="open()">新增岗位</el-button></PageHeader>
    <div class="permission-chain"><div><b>业务角色</b><span>运营 / 客服 / 规划师</span><small>决定能做什么</small></div><i>＋</i><div class="active"><b>数据岗位</b><span>本人 / 本部门 / 部门及下级 / 公司</span><small>决定能看哪些数据</small></div><i>→</i><div><b>员工有效权限</b><span>功能权限 ∩ 数据范围</span><small>服务端统一鉴权</small></div></div>
    <main class="surface position-shell"><div class="position-toolbar"><div><el-input v-model="keyword" clearable prefix-icon="Search" placeholder="搜索岗位名称、编码或说明"/><el-select v-model="scopeFilter" clearable placeholder="数据范围"><el-option v-for="item in scopeOptions" :key="item.value" :label="item.label" :value="item.value"/></el-select></div><span>共 {{ visibleRows.length }} 个数据岗位</span></div>
      <el-table :data="visibleRows" row-key="id"><el-table-column prop="name" label="岗位名称" min-width="170"><template #default="{row}"><button class="position-link" @click="open(row,'preview')">{{ row.name }}</button><small>{{ row.code }}</small></template></el-table-column><el-table-column label="数据范围" min-width="185"><template #default="{row}"><el-tag>{{ scopeLabel(row.scope) }}</el-tag><span v-if="row.scope==='CUSTOM'">{{ row.organizations.length }} 个组织</span></template></el-table-column><el-table-column prop="description" label="范围说明" min-width="280"/><el-table-column prop="members" label="关联员工" width="110"><template #default="{row}"><el-button link type="primary" @click="open(row,'members')">{{ row.members }} 人</el-button></template></el-table-column><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{ row.status==='ACTIVE'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="175" fixed="right"><template #default="{row}"><el-button link type="primary" @click="open(row,'preview')">预览</el-button><el-button link type="primary" @click="open(row,'edit')">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table>
    </main>
    <el-drawer v-model="drawer" :title="mode==='members'?'关联员工':mode==='preview'?'数据范围预览':current?'编辑岗位':'新增岗位'" size="580px">
      <template v-if="mode==='members'"><el-alert title="一个员工默认绑定一个数据岗位；特殊临时授权应单独审批，不通过业务角色扩权。" type="info" :closable="false" show-icon/><el-input prefix-icon="Search" placeholder="搜索员工编号或姓名"/><el-empty description="员工关联选择器演示"/></template>
      <template v-else-if="mode==='preview'"><div class="scope-preview"><span>{{ current?.name }}</span><b>{{ scopeLabel(current!.scope) }}</b><p>{{ current?.description }}</p><el-tag v-for="item in current?.organizations" :key="item">{{ item }}</el-tag><small>范围同时作用于列表、详情、搜索、统计、导出和接口。</small></div></template>
      <el-form v-else label-position="top"><el-form-item label="岗位名称" required><el-input v-model="form.name" placeholder="如小组管理岗"/></el-form-item><el-form-item label="岗位编码"><el-input v-model="form.code" disabled/></el-form-item><el-form-item label="数据范围" required><el-radio-group v-model="form.scope" class="scope-radio"><el-radio v-for="item in scopeOptions" :key="item.value" :value="item.value">{{ item.label }}</el-radio></el-radio-group></el-form-item><el-form-item v-if="form.scope==='CUSTOM'" label="指定组织" required><el-select v-model="form.organizations" multiple filterable style="width:100%" placeholder="可选择多个部门或小组"><el-option label="一转事业部" value="一转事业部"/><el-option label="客户运营部" value="客户运营部"/><el-option label="教务交付部" value="教务交付部"/></el-select></el-form-item><el-form-item label="岗位说明"><el-input v-model="form.description" type="textarea" :rows="3"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio value="ACTIVE">启用</el-radio><el-radio value="INACTIVE">停用</el-radio></el-radio-group></el-form-item><div class="drawer-actions"><el-button @click="drawer=false">取消</el-button><el-button type="primary" @click="save">保存岗位</el-button></div></el-form>
    </el-drawer>
  </section>
</template>

<style scoped>
.position-page{--ink:#172842}.permission-chain{display:grid;grid-template-columns:1fr auto 1fr auto 1fr;align-items:center;gap:16px;margin-bottom:20px}.permission-chain>div{background:#fff;border:1px solid #dce6f5;border-radius:16px;padding:18px 20px;display:grid;gap:4px;box-shadow:0 8px 24px rgba(40,75,120,.06)}.permission-chain>div.active{border-color:#7fb0fa;background:linear-gradient(135deg,#edf5ff,#fff)}.permission-chain b{font-size:17px;color:var(--ink)}.permission-chain span{color:#526987}.permission-chain small{color:#8ca0ba}.permission-chain i{font-style:normal;font-size:24px;color:#78a7e8}.position-shell{overflow:hidden}.position-toolbar{display:flex;align-items:center;justify-content:space-between;padding:18px 20px;border-bottom:1px solid #e8eef6;color:#7b8da6}.position-toolbar>div{display:flex;gap:12px}.position-toolbar .el-input{width:310px}.position-toolbar .el-select{width:180px}.position-link{display:block;border:0;background:none;color:#176ee8;font-weight:700;cursor:pointer;padding:0}.position-link+small{display:block;color:#9aabc1;margin-top:4px}.el-table .el-tag+span{margin-left:8px;color:#687d98}.scope-radio{display:grid;grid-template-columns:1fr 1fr;gap:10px;width:100%}.scope-radio .el-radio{margin:0;border:1px solid #dce6f3;border-radius:9px;padding:12px}.switch-copy{margin-left:10px;color:#617692}.drawer-actions{display:flex;justify-content:flex-end;margin-top:28px}.scope-preview{display:grid;gap:14px;padding:22px;background:linear-gradient(145deg,#f0f6ff,#fff);border:1px solid #d7e6fb;border-radius:16px}.scope-preview>span{color:#7086a2}.scope-preview>b{font-size:28px;color:#183354}.scope-preview p{color:#536a86}.scope-preview small{display:block;margin-top:16px;color:#8194ad}@media(max-width:900px){.permission-chain{grid-template-columns:1fr}.permission-chain>i{text-align:center}.position-toolbar{align-items:flex-start;gap:12px}.position-toolbar>div{flex-direction:column}.position-toolbar .el-input,.position-toolbar .el-select{width:100%}}
</style>
