<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import '../styles/role.css'

type Role = { id:number; code:string; name:string; type:'BUILT_IN'|'CUSTOM'; description:string; members:number; status:'ACTIVE'|'INACTIVE'; operationSummary:string; dataScope:string; dataScopeLabel:string }
const keyword=ref(''), status=ref(''), drawer=ref(false), drawerMode=ref<'detail'|'member'|'operation'|'data'>('detail'), current=ref<Role|null>(null)
const roles=ref<Role[]>([
  {id:1,code:'ROLE_SUPER_ADMIN',name:'超级管理员',type:'BUILT_IN',description:'管理合数BOSS全部功能与配置',members:2,status:'ACTIVE',operationSummary:'全部菜单及操作',dataScope:'ALL',dataScopeLabel:'全部数据'},
  {id:2,code:'ROLE_SALES_MANAGER',name:'销售部门负责人',type:'CUSTOM',description:'负责销售团队、线索分配及经营数据',members:6,status:'ACTIVE',operationSummary:'线索、客户、报表等 32 项',dataScope:'ORG_AND_CHILDREN',dataScopeLabel:'本组织及下级'},
  {id:3,code:'ROLE_CONSULTANT',name:'课程顾问',type:'CUSTOM',description:'承接线索并维护本人客户',members:38,status:'ACTIVE',operationSummary:'线索、客户等 18 项',dataScope:'SELF',dataScopeLabel:'本人数据'},
  {id:4,code:'ROLE_CUSTOMER_SERVICE',name:'客户服务',type:'CUSTOM',description:'处理客户咨询、工单与售后协作',members:12,status:'ACTIVE',operationSummary:'客户、客服等 21 项',dataScope:'CUSTOM',dataScopeLabel:'客户服务部'},
  {id:5,code:'ROLE_FINANCE',name:'财务专员',type:'CUSTOM',description:'查询订单并处理支付、退款业务',members:4,status:'ACTIVE',operationSummary:'订单、支付等 16 项',dataScope:'ORG',dataScopeLabel:'本组织'},
  {id:6,code:'ROLE_AUDITOR',name:'审计查看员',type:'CUSTOM',description:'只读查看授权范围内的日志与报表',members:1,status:'INACTIVE',operationSummary:'只读权限 9 项',dataScope:'CUSTOM',dataScopeLabel:'指定组织（3）'}
])
const form=reactive({name:'',code:'',description:'',status:'ACTIVE'}), scope=ref('SELF'), customOrganizations=ref<string[]>([])
const visibleRoles=computed(()=>{const term=keyword.value.trim().toLowerCase();return roles.value.filter(row=>(!status.value||row.status===status.value)&&(!term||`${row.code}${row.name}${row.description}`.toLowerCase().includes(term)))})
const drawerTitle=computed(()=>drawerMode.value==='member'?'关联员工':drawerMode.value==='operation'?'操作权限':drawerMode.value==='data'?'数据权限':'角色详情')
function open(mode:typeof drawerMode.value,row:Role){current.value=row;drawerMode.value=mode;scope.value=row.dataScope;customOrganizations.value=row.dataScope==='CUSTOM'?[row.dataScopeLabel]:[];drawer.value=true}
function createRole(){current.value=null;Object.assign(form,{name:'',code:'保存后自动生成',description:'',status:'ACTIVE'});drawerMode.value='detail';drawer.value=true}
function saveScope(){if(!current.value)return;current.value.dataScope=scope.value;current.value.dataScopeLabel={ALL:'全部数据',ORG_AND_CHILDREN:'本组织及下级',ORG:'本组织',SELF:'本人数据',CUSTOM:`指定组织（${customOrganizations.value.length}）`}[scope.value]||'未配置';drawer.value=false;ElMessage.success('数据权限已更新')}
async function removeRole(row:Role){if(row.type==='BUILT_IN'){ElMessage.warning('系统内置角色不可删除');return}if(row.members){await ElMessageBox.alert(`该角色仍关联 ${row.members} 名员工，请先解除关联。`,'暂时无法删除',{type:'warning'});return}roles.value=roles.value.filter(item=>item.id!==row.id);ElMessage.success('角色已删除')}
</script>

<template>
  <section class="page role-page">
    <PageHeader eyebrow="HESHU BOSS · ACCESS CONTROL" title="角色管理" description="按角色统一配置员工关联、功能操作和业务数据可见范围。"><el-button type="primary" @click="createRole">新增角色</el-button></PageHeader>
    <div class="role-summary"><div><span>角色总数</span><b>{{ roles.length }}</b></div><div><span>启用角色</span><b>{{ roles.filter(item=>item.status==='ACTIVE').length }}</b></div><div><span>已关联员工</span><b>{{ roles.reduce((sum,item)=>sum+item.members,0) }}</b></div><p><strong>权限分层</strong><span>操作权限决定“能做什么”，数据权限决定“能看哪些业务数据”。</span></p></div>
    <main class="surface role-table-shell">
      <div class="role-toolbar"><div><el-select v-model="status" clearable placeholder="角色状态"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select><el-input v-model="keyword" clearable prefix-icon="Search" placeholder="搜索角色名称、编码或描述"/></div><span>共 {{ visibleRoles.length }} 个角色</span></div>
      <el-table :data="visibleRoles" row-key="id"><el-table-column prop="name" label="角色名称" min-width="180"><template #default="{row}"><button class="org-name-link" @click="open('detail',row)">{{ row.name }}</button><el-tag v-if="row.type==='BUILT_IN'" class="role-built-in" size="small">内置</el-tag><small class="role-code">{{ row.code }}</small></template></el-table-column><el-table-column prop="description" label="角色描述" min-width="240" show-overflow-tooltip/><el-table-column prop="members" label="关联员工" width="110"><template #default="{row}"><el-button link type="primary" @click="open('member',row)">{{ row.members }} 人</el-button></template></el-table-column><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{ row.status==='ACTIVE'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="操作权限" min-width="180"><template #default="{row}"><button class="permission-link" @click="open('operation',row)"><b>配置权限</b><span>{{ row.operationSummary }}</span></button></template></el-table-column><el-table-column label="数据权限" min-width="190"><template #default="{row}"><button class="permission-link data" @click="open('data',row)"><b>配置数据权限</b><span>{{ row.dataScopeLabel }}</span></button></template></el-table-column><el-table-column label="操作" width="165" fixed="right"><template #default="{row}"><el-button link type="primary" @click="open('detail',row)">详情</el-button><el-button link type="primary" @click="open('member',row)">关联</el-button><el-button link type="danger" @click="removeRole(row)">删除</el-button></template></el-table-column></el-table>
      <div class="employee-pagination"><span>角色权限变更将记录操作日志</span><el-pagination background layout="prev, pager, next, total" :total="visibleRoles.length" :page-size="10"/></div>
    </main>
    <el-drawer v-model="drawer" :title="drawerTitle" size="560px"><template v-if="drawerMode==='data' && current"><div class="permission-explain"><b>{{ current.name }}</b><span>数据范围会同时约束列表、详情、统计和导出结果。</span></div><el-radio-group v-model="scope" class="scope-list"><el-radio value="ALL"><b>全部数据</b><span>可查看系统内全部业务数据</span></el-radio><el-radio value="ORG_AND_CHILDREN"><b>本组织及下级</b><span>员工所属组织及全部下级组织</span></el-radio><el-radio value="ORG"><b>本组织</b><span>仅员工直接所属组织</span></el-radio><el-radio value="SELF"><b>本人数据</b><span>仅本人负责、创建或被明确协作的数据</span></el-radio><el-radio value="CUSTOM"><b>自定义组织</b><span>从公司、部门和小组中指定范围</span></el-radio></el-radio-group><el-select v-if="scope==='CUSTOM'" v-model="customOrganizations" multiple placeholder="请选择组织" style="width:100%"><el-option label="一转销售部" value="一转销售部"/><el-option label="客户服务部" value="客户服务部"/><el-option label="财务部" value="财务部"/></el-select><div class="drawer-footer"><el-button @click="drawer=false">取消</el-button><el-button type="primary" @click="saveScope">保存数据权限</el-button></div></template><template v-else-if="drawerMode==='operation' && current"><div class="permission-explain"><b>{{ current.name }}</b><span>按菜单配置查看、新增、编辑、删除、导入、导出等操作；敏感字段明文权限在此单独授权。</span></div><el-tree :data="[{label:'线索中心',children:[{label:'线索查看 / 分配 / 导出'},{label:'活码与渠道配置'}]},{label:'客户中心',children:[{label:'客户查看 / 编辑 / 移交'},{label:'手机号与邮箱明文查看'}]},{label:'系统管理',children:[{label:'组织员工管理'},{label:'角色与菜单管理'}]}]" show-checkbox default-expand-all/></template><template v-else-if="drawerMode==='member' && current"><div class="permission-explain"><b>{{ current.name }} · {{ current.members }} 人</b><span>角色只与员工直接关联，不根据岗位文本自动继承。</span></div><el-input prefix-icon="Search" placeholder="搜索员工编号或姓名"/><el-empty description="成员选择器演示"/></template><template v-else><el-form label-position="top"><el-form-item label="角色名称"><el-input :model-value="current?.name||form.name" placeholder="请输入角色名称"/></el-form-item><el-form-item label="角色编码"><el-input :model-value="current?.code||form.code" disabled/></el-form-item><el-form-item label="角色描述"><el-input :model-value="current?.description||form.description" type="textarea" :rows="3"/></el-form-item><el-form-item label="状态"><el-radio-group :model-value="current?.status||form.status"><el-radio value="ACTIVE">启用</el-radio><el-radio value="INACTIVE">停用</el-radio></el-radio-group></el-form-item></el-form></template></el-drawer>
  </section>
</template>
