<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import '../styles/system-tools.css'
import '../styles/system-tools-overrides.css'

const route=useRoute(), keyword=ref(''), status=ref(''), activeTab=ref(''), dialog=ref(false), drawer=ref(false), current=ref<any>({}), form=reactive<any>({})
const landingEditorVisible=ref(false),editingLanding=ref<any>(null),landingPreviewVisible=ref(false),previewLanding=ref<any>(null)
const redirectModeOptions=['获客助手','小程序','微信客户']
const landingForm=reactive({name:'',h5Url:'',redirectMode:'获客助手',fallbackModes:[] as string[]})
const pageType=computed(()=>route.path.startsWith('/system/sms')?'sms':route.path.startsWith('/system/regions')?'regions':'configurations')
const pageMeta=computed(()=>pageType.value==='configurations'&&activeTab.value==='landing'?['落地页配置','集中维护落地页地址、跳转方式与兜底优先级。']:({sms:['短信管理','复用历史短信服务，统一管理短信签名、模板与发送回执。'],configurations:['配置管理','集中维护企微、小程序、店铺和落地页接入配置。'],regions:['地区管理','接入国家地区标准数据，按国家、一级行政区、二级行政区维护。']}[pageType.value]||['系统工具','系统配置']))
const tabs=computed(()=>pageType.value==='sms'?[['signatures','签名管理'],['templates','短信模板'],['results','发送结果']]:[['wecom','企微配置'],['mini','小程序配置'],['stores','店铺配置'],['landing','落地页配置']])
const smsRows:Record<string,any[]>=reactive({signatures:[{no:'SIGN001',name:'合数教育',provider:'阿里云短信',audit:'APPROVED',status:'ACTIVE'}],templates:[{no:'TPL001',name:'课程提醒',sign:'合数教育',providerNo:'SMS_238901',audit:'APPROVED',status:'ACTIVE'}],results:[{no:'SMS202608170001',providerNo:'20260817A1092',result:'已送达',code:'OK',pieces:1,time:'2026-08-17 09:30:23'}]})
const configRows:Record<string,any[]>=reactive({wecom:[{code:'WECOM_MAIN',name:'合数教育企业微信',target:'CorpID ww****21',status:'ACTIVE',updated:'2026-08-17 08:10:00'}],mini:[{code:'MP_SCRM',name:'合数客户助手',target:'AppID wx****93',status:'ACTIVE',updated:'2026-08-16 18:20:00'}],stores:[{code:'STORE_DY_001',name:'合数教育抖音店',target:'抖音 / 一转销售部',status:'ACTIVE',updated:'2026-08-15 16:00:00'}],landing:[
  {code:'LP_SALES_01',name:'一转课程咨询落地页',h5Url:'https://h5.heshu.cn/course-consult',redirectMode:'获客助手',fallbackModes:['小程序','微信客户'],status:'ACTIVE',createdAt:'2026-08-28 10:20:00'},
  {code:'LP_LIVE_02',name:'直播活动落地页',h5Url:'https://h5.heshu.cn/live-signup',redirectMode:'小程序',fallbackModes:['获客助手','微信客户'],status:'ACTIVE',createdAt:'2026-08-25 16:45:00'},
  {code:'LP_MINI_03',name:'停用后转小程序',h5Url:'https://h5.heshu.cn/mini-backup',redirectMode:'微信客户',fallbackModes:['小程序','获客助手'],status:'INACTIVE',createdAt:'2025-03-07 17:18:15'}
]})
const regions=ref([{id:'CN',name:'中国',level:'COUNTRY',type:'国家',code:'156',status:'ACTIVE',children:[{id:'CN-11',name:'北京市',level:'LEVEL_1',type:'直辖市（一级行政区）',code:'110000',status:'ACTIVE',children:[{id:'CN-11-01',name:'北京市市辖区',level:'LEVEL_2',type:'市辖区（二级行政区）',code:'110100',status:'ACTIVE'}]},{id:'CN-42',name:'湖北省',level:'LEVEL_1',type:'省（一级行政区）',code:'420000',status:'ACTIVE',children:[{id:'CN-42-01',name:'武汉市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'420100',status:'ACTIVE'},{id:'CN-42-06',name:'襄阳市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'420600',status:'ACTIVE'}]},{id:'CN-44',name:'广东省',level:'LEVEL_1',type:'省（一级行政区）',code:'440000',status:'ACTIVE',children:[{id:'CN-44-01',name:'广州市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'440100',status:'ACTIVE'},{id:'CN-44-03',name:'深圳市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'440300',status:'ACTIVE'}]},{id:'CN-45',name:'广西壮族自治区',level:'LEVEL_1',type:'自治区（一级行政区）',code:'450000',status:'ACTIVE',children:[{id:'CN-45-01',name:'南宁市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'450100',status:'ACTIVE'}]},{id:'CN-81',name:'香港特别行政区',level:'LEVEL_1',type:'特别行政区（一级行政区）',code:'810000',status:'ACTIVE',children:[]}]}])
const currentRows=computed(()=>pageType.value==='sms'?smsRows[activeTab.value]||[]:configRows[activeTab.value]||[])
const landingRows=computed(()=>configRows.landing.filter(row=>(!keyword.value.trim()||row.name.includes(keyword.value.trim()))&&(!status.value||row.status===status.value)))
function init(){const segment=route.path.split('/').pop()||'';activeTab.value=tabs.value.some(item=>item[0]===segment)?segment:tabs.value[0]?.[0]||'';keyword.value='';status.value=''}watch(()=>route.path,init,{immediate:true})
function reset(){keyword.value='';status.value=''}
function openForm(row?:any){current.value=row||{};Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,row||{});dialog.value=true}
function showDetail(row:any){current.value=row;drawer.value=true}
function openLandingEditor(row:any){
  editingLanding.value=row
  landingForm.name=row.name
  landingForm.h5Url=row.h5Url
  landingForm.redirectMode=row.redirectMode
  landingForm.fallbackModes=[...row.fallbackModes]
  landingEditorVisible.value=true
}
function changeRedirectMode(value:string){
  const available=redirectModeOptions.filter(item=>item!==value)
  landingForm.fallbackModes=[...landingForm.fallbackModes.filter(item=>available.includes(item)),...available.filter(item=>!landingForm.fallbackModes.includes(item))]
}
function moveFallbackMode(index:number,direction:-1|1){
  const target=index+direction
  if(target<0||target>=landingForm.fallbackModes.length)return
  const next=[...landingForm.fallbackModes]
  ;[next[index],next[target]]=[next[target],next[index]]
  landingForm.fallbackModes=next
}
function saveLanding(){
  if(!landingForm.name.trim())return ElMessage.warning('请输入落地页名称')
  if(!/^https?:\/\//i.test(landingForm.h5Url.trim()))return ElMessage.warning('请输入以 http:// 或 https:// 开头的H5地址')
  if(!landingForm.redirectMode)return ElMessage.warning('请选择跳转方式')
  Object.assign(editingLanding.value,{name:landingForm.name.trim(),h5Url:landingForm.h5Url.trim(),redirectMode:landingForm.redirectMode,fallbackModes:[...landingForm.fallbackModes]})
  landingEditorVisible.value=false
  ElMessage.success('落地页配置已更新')
}
function toggleLanding(row:any){row.status=row.status==='ACTIVE'?'INACTIVE':'ACTIVE';ElMessage.success(`落地页已${row.status==='ACTIVE'?'启用':'停用'}`)}
function openLandingPreview(row:any){previewLanding.value=row;landingPreviewVisible.value=true}
async function deleteLanding(row:any){
  if(row.status!=='INACTIVE')return ElMessage.warning('仅停用状态允许删除')
  try{await ElMessageBox.confirm(`确认删除落地页“${row.name}”吗？`,'删除落地页',{type:'warning',confirmButtonText:'确认删除',cancelButtonText:'取消'});const index=configRows.landing.indexOf(row);if(index>=0)configRows.landing.splice(index,1);ElMessage.success('落地页已删除')}catch{}
}
</script>

<template><section class="page system-tools-page"><PageHeader eyebrow="HESHU BOSS · SYSTEM SERVICES" :title="pageMeta[0]" :description="pageMeta[1]"><el-button v-if="pageType==='regions'" type="primary">同步国家地区</el-button><el-button v-else-if="activeTab!=='landing'" type="primary" @click="openForm()">新增配置</el-button></PageHeader>
<template v-if="pageType==='sms'||pageType==='configurations'">
  <div class="surface subpage-tabs"><button v-for="tab in tabs" :key="tab[0]" :class="{active:activeTab===tab[0]}" @click="activeTab=tab[0]">{{ tab[1] }}</button></div>
  <template v-if="pageType==='configurations'&&activeTab==='landing'">
    <div class="surface tools-filter landing-filter"><el-form inline><el-form-item label="落地页名称"><el-input v-model="keyword" clearable placeholder="请输入落地页名称"/></el-form-item><el-form-item label="落地页状态"><el-select v-model="status" clearable placeholder="请选择"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item><el-button type="primary">搜索</el-button><el-button @click="reset">重置</el-button></el-form></div>
    <main class="surface tools-table landing-table"><div class="tools-table-head"><strong>落地页列表</strong><span>共 {{ landingRows.length }} 条</span></div><el-table :data="landingRows" row-key="code"><el-table-column type="selection" width="54"/><el-table-column prop="code" label="落地页编码" width="145"><template #default="{row}"><code class="landing-code">{{ row.code }}</code></template></el-table-column><el-table-column prop="name" label="落地页名称" min-width="190"/><el-table-column prop="h5Url" label="H5地址" min-width="245" show-overflow-tooltip><template #default="{row}"><span class="h5-url">{{ row.h5Url }}</span></template></el-table-column><el-table-column label="跳转方式" min-width="130"><template #default="{row}"><el-tag effect="plain">{{ row.redirectMode }}</el-tag></template></el-table-column><el-table-column label="兜底方式优先级" min-width="250"><template #default="{row}"><div class="redirect-priority"><span v-for="(item,index) in row.fallbackModes" :key="item"><i>{{ index+1 }}</i>{{ item }}</span><em v-if="!row.fallbackModes.length">无兜底方式</em></div></template></el-table-column><el-table-column label="落地页状态" width="105"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{ row.status==='ACTIVE'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="创建时间" width="175"/><el-table-column label="操作" width="245" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openLandingPreview(row)">预览</el-button><el-button link type="primary" @click="openLandingEditor(row)">编辑</el-button><el-button v-if="row.status==='ACTIVE'" link type="warning" @click="toggleLanding(row)">停用</el-button><template v-else><el-button link type="success" @click="toggleLanding(row)">启用</el-button><el-button link type="danger" @click="deleteLanding(row)">删除</el-button></template></template></el-table-column></el-table></main>
  </template>
  <template v-else>
    <div class="surface tools-filter"><el-form inline><el-form-item label="关键词"><el-input v-model="keyword" clearable placeholder="输入编码或名称"/></el-form-item><el-form-item label="状态"><el-select v-model="status" clearable placeholder="全部状态"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item><el-button type="primary">查询</el-button><el-button @click="reset">重置</el-button></el-form></div><main class="surface tools-table"><div class="tools-table-head"><el-button type="primary" @click="openForm()">新增</el-button><span>{{ tabs.find(i=>i[0]===activeTab)?.[1] }}</span></div><el-table :data="currentRows"><el-table-column v-for="key in Object.keys(currentRows[0]||{})" :key="key" :prop="key" :label="({no:'编码/单号',code:'配置编码',name:'名称',target:'对象/接入信息',sign:'签名',template:'模板',time:'时间',status:'状态',provider:'供应商',audit:'审核状态',providerNo:'供应商编号',result:'结果',pieces:'计费条数',updated:'更新时间'} as any)[key]||key" min-width="130"/><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" @click="showDetail(row)">详情</el-button><el-button link type="primary" @click="openForm(row)">编辑</el-button></template></el-table-column></el-table></main>
  </template>
</template>
<template v-else><div class="region-guide"><b>国家地区层级</b><span>国家</span><i>›</i><span>一级行政区：省、自治区、直辖市、特别行政区</span><i>›</i><span>二级行政区：地级市、自治州、地区、盟、市辖区</span></div><div class="surface tools-filter"><el-form inline><el-form-item label="地区名称/编码"><el-input v-model="keyword" clearable placeholder="请输入"/></el-form-item><el-form-item label="状态"><el-select v-model="status" clearable placeholder="全部状态"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item><el-button type="primary">查询</el-button><el-button @click="reset">重置</el-button></el-form></div><main class="surface tools-table"><div class="tools-table-head"><el-button type="primary" @click="openForm()">新增地区</el-button><span>地区编码接入国家地区标准数据源</span></div><el-table :data="regions" row-key="id" default-expand-all><el-table-column prop="name" label="国家/地区名称" min-width="220"/><el-table-column prop="code" label="标准编码" width="130"/><el-table-column prop="level" label="行政层级" width="140"><template #default="{row}"><el-tag :type="row.level==='COUNTRY'?'success':row.level==='LEVEL_1'?'primary':'info'">{{ row.level==='COUNTRY'?'国家':row.level==='LEVEL_1'?'一级行政区':'二级行政区' }}</el-tag></template></el-table-column><el-table-column prop="type" label="法定类型" min-width="230"/><el-table-column prop="status" label="状态" width="100"><template #default="{row}"><el-tag type="success">启用</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button link type="primary" @click="openForm(row)">编辑</el-button><el-button link type="primary" :disabled="row.level==='LEVEL_2'" @click="openForm()">新增下级</el-button></template></el-table-column></el-table></main></template>
<el-dialog v-model="landingEditorVisible" title="编辑落地页" width="680px"><el-form label-position="top"><el-form-item label="落地页名称" required><el-input v-model="landingForm.name" maxlength="50" show-word-limit placeholder="请输入落地页名称"/></el-form-item><el-form-item label="H5地址" required><el-input v-model="landingForm.h5Url" placeholder="请输入以 https:// 开头的H5地址"/></el-form-item><el-form-item label="跳转方式" required><el-radio-group v-model="landingForm.redirectMode" @change="changeRedirectMode"><el-radio-button v-for="item in redirectModeOptions" :key="item" :value="item">{{ item }}</el-radio-button></el-radio-group><small class="landing-form-tip">跳转方式为唯一值，落地页优先执行该方式。</small></el-form-item><el-form-item label="兜底方式优先级"><div class="priority-editor"><div v-for="(item,index) in landingForm.fallbackModes" :key="item"><span><i>{{ index+1 }}</i>{{ item }}</span><div><el-button size="small" :disabled="index===0" @click="moveFallbackMode(index,-1)">上移</el-button><el-button size="small" :disabled="index===landingForm.fallbackModes.length-1" @click="moveFallbackMode(index,1)">下移</el-button></div></div></div><small class="landing-form-tip">主跳转方式不可用时，系统按以上顺序依次尝试其他方式。</small></el-form-item></el-form><template #footer><el-button @click="landingEditorVisible=false">取消</el-button><el-button type="primary" @click="saveLanding">保存</el-button></template></el-dialog>
<el-dialog v-model="landingPreviewVisible" title="手机端预览" width="520px" class="landing-preview-dialog"><div v-if="previewLanding" class="phone-preview"><div class="phone-speaker"></div><div class="preview-hero"><small>{{ previewLanding.code }} · {{ previewLanding.h5Url.replace(/^https?:\/\//,'') }}</small><h2>{{ previewLanding.name }}</h2></div><div class="preview-body"><div class="preview-offer"><strong>¥ 88</strong><span>新人权益礼包</span><button>立即领取</button></div><p>点击后优先跳转至「{{ previewLanding.redirectMode }}」</p><small>不可用时依次尝试：{{ previewLanding.fallbackModes.join(' → ') || '无' }}</small></div></div></el-dialog>
<el-dialog v-model="dialog" :title="current.id?'编辑':'新增'" width="600px"><el-form label-position="top"><div class="form-grid"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="编码/应用标识"><el-input v-model="form.app" placeholder="由对应服务校验唯一性"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status" style="width:100%"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="form.remark"/></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="dialog=false;ElMessage.success('已保存')">保存</el-button></template></el-dialog><el-drawer v-model="drawer" title="详情" size="520px"><el-descriptions :column="1" border><el-descriptions-item v-for="(value,key) in current" :key="key" :label="String(key)">{{ value }}</el-descriptions-item></el-descriptions></el-drawer>
</section></template>

<style scoped>
.landing-filter{padding:18px 20px}.landing-filter :deep(.el-form){display:flex;align-items:flex-end;gap:10px}.landing-filter :deep(.el-form-item){margin:0}.landing-filter :deep(.el-input){width:260px}.landing-filter :deep(.el-select){width:220px}.landing-table{padding:0 20px 20px}.landing-table .tools-table-head{justify-content:flex-start;gap:12px}.landing-table .tools-table-head strong{color:#172945;font-size:17px}.redirect-priority{display:flex;flex-wrap:wrap;gap:6px}.redirect-priority span{display:inline-flex;align-items:center;gap:5px;padding:4px 8px;border-radius:13px;background:#edf5ff;color:#2b68b6;font-size:12px}.redirect-priority i,.priority-editor i{width:18px;height:18px;display:inline-grid;place-items:center;border-radius:50%;background:#2875e6;color:#fff;font-size:10px;font-style:normal}.landing-form-tip{display:block;margin-top:7px;color:#8796aa}.priority-editor{width:100%;display:grid;gap:8px}.priority-editor>div{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;border:1px solid #dce6f2;border-radius:8px;background:#f8faff}.priority-editor span{display:flex;align-items:center;gap:8px;color:#20344f;font-weight:600}
.landing-code{padding:3px 7px;border:1px solid #d8e5f5;border-radius:5px;background:#f5f9ff;color:#356aa6}.h5-url{color:#55708f}.phone-preview{position:relative;width:360px;height:650px;margin:0 auto 12px;overflow:hidden;border:1px solid #b7c4d2;border-radius:34px;background:#f7f9fc;box-shadow:0 10px 28px rgba(24,45,76,.14)}.phone-speaker{position:absolute;z-index:2;top:16px;left:50%;width:90px;height:9px;transform:translateX(-50%);border-radius:10px;background:#68788c}.preview-hero{padding:70px 32px 26px;background:linear-gradient(145deg,#1978f3,#2548da);color:#fff}.preview-hero small{opacity:.88}.preview-hero h2{margin:12px 0 0;font-size:25px}.preview-body{padding:28px 24px;text-align:center}.preview-offer{display:grid;gap:10px;padding:30px 20px 22px;border:1px solid #dce4ee;border-radius:14px;background:#fff}.preview-offer strong{color:#2475ed;font-size:42px}.preview-offer span{color:#66758a;font-size:18px}.preview-offer button{margin-top:8px;padding:13px;border:0;border-radius:7px;background:#2475ed;color:#fff;font-size:19px;cursor:default}.preview-body p{margin:24px 0 8px;color:#65758a}.preview-body>small{color:#95a1b1}
</style>
