<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { ElMessage } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import '../styles/system-tools.css'
import '../styles/system-tools-overrides.css'

const route=useRoute(), keyword=ref(''), status=ref(''), activeTab=ref(''), dialog=ref(false), drawer=ref(false), current=ref<any>({}), form=reactive<any>({})
const pageType=computed(()=>route.path.startsWith('/system/sms')?'sms':route.path.startsWith('/system/regions')?'regions':'configurations')
const pageMeta=computed(()=>({sms:['短信管理','复用历史短信服务，统一管理短信签名、模板与发送回执。'],configurations:['配置管理','集中维护企微、小程序、店铺和落地页接入配置。'],regions:['地区管理','接入国家地区标准数据，按国家、一级行政区、二级行政区维护。']}[pageType.value]||['系统工具','系统配置']))
const tabs=computed(()=>pageType.value==='sms'?[['signatures','签名管理'],['templates','短信模板'],['results','发送结果']]:[['wecom','企微配置'],['mini','小程序配置'],['stores','店铺配置'],['landing','落地页配置']])
const smsRows:Record<string,any[]>=reactive({signatures:[{no:'SIGN001',name:'合数教育',provider:'阿里云短信',audit:'APPROVED',status:'ACTIVE'}],templates:[{no:'TPL001',name:'课程提醒',sign:'合数教育',providerNo:'SMS_238901',audit:'APPROVED',status:'ACTIVE'}],results:[{no:'SMS202608170001',providerNo:'20260817A1092',result:'已送达',code:'OK',pieces:1,time:'2026-08-17 09:30:23'}]})
const configRows:Record<string,any[]>=reactive({wecom:[{code:'WECOM_MAIN',name:'合数教育企业微信',target:'CorpID ww****21',status:'ACTIVE',updated:'2026-08-17 08:10:00'}],mini:[{code:'MP_SCRM',name:'合数客户助手',target:'AppID wx****93',status:'ACTIVE',updated:'2026-08-16 18:20:00'}],stores:[{code:'STORE_DY_001',name:'合数教育抖音店',target:'抖音 / 一转销售部',status:'ACTIVE',updated:'2026-08-15 16:00:00'}],landing:[{code:'LP_SUMMER_01',name:'暑期直播落地页',target:'https://m.heshu.cn/summer',status:'INACTIVE',updated:'2026-08-14 10:00:00'}]})
const regions=ref([{id:'CN',name:'中国',level:'COUNTRY',type:'国家',code:'156',status:'ACTIVE',children:[{id:'CN-11',name:'北京市',level:'LEVEL_1',type:'直辖市（一级行政区）',code:'110000',status:'ACTIVE',children:[{id:'CN-11-01',name:'北京市市辖区',level:'LEVEL_2',type:'市辖区（二级行政区）',code:'110100',status:'ACTIVE'}]},{id:'CN-42',name:'湖北省',level:'LEVEL_1',type:'省（一级行政区）',code:'420000',status:'ACTIVE',children:[{id:'CN-42-01',name:'武汉市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'420100',status:'ACTIVE'},{id:'CN-42-06',name:'襄阳市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'420600',status:'ACTIVE'}]},{id:'CN-44',name:'广东省',level:'LEVEL_1',type:'省（一级行政区）',code:'440000',status:'ACTIVE',children:[{id:'CN-44-01',name:'广州市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'440100',status:'ACTIVE'},{id:'CN-44-03',name:'深圳市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'440300',status:'ACTIVE'}]},{id:'CN-45',name:'广西壮族自治区',level:'LEVEL_1',type:'自治区（一级行政区）',code:'450000',status:'ACTIVE',children:[{id:'CN-45-01',name:'南宁市',level:'LEVEL_2',type:'地级市（二级行政区）',code:'450100',status:'ACTIVE'}]},{id:'CN-81',name:'香港特别行政区',level:'LEVEL_1',type:'特别行政区（一级行政区）',code:'810000',status:'ACTIVE',children:[]}]}])
const currentRows=computed(()=>pageType.value==='sms'?smsRows[activeTab.value]||[]:configRows[activeTab.value]||[])
function init(){const segment=route.path.split('/').pop()||'';activeTab.value=tabs.value.some(item=>item[0]===segment)?segment:tabs.value[0]?.[0]||'';keyword.value='';status.value=''}watch(()=>route.path,init,{immediate:true})
function reset(){keyword.value='';status.value=''}
function openForm(row?:any){current.value=row||{};Object.keys(form).forEach(k=>delete form[k]);Object.assign(form,row||{});dialog.value=true}
function showDetail(row:any){current.value=row;drawer.value=true}
</script>

<template><section class="page system-tools-page"><PageHeader eyebrow="HESHU BOSS · SYSTEM SERVICES" :title="pageMeta[0]" :description="pageMeta[1]"><el-button v-if="pageType==='regions'" type="primary">同步国家地区</el-button><el-button v-if="pageType!=='regions'" type="primary" @click="openForm()">新增配置</el-button></PageHeader>
<template v-if="pageType==='sms'||pageType==='configurations'"><div class="surface subpage-tabs"><button v-for="tab in tabs" :key="tab[0]" :class="{active:activeTab===tab[0]}" @click="activeTab=tab[0]">{{ tab[1] }}</button></div><div class="surface tools-filter"><el-form inline><el-form-item label="关键词"><el-input v-model="keyword" clearable placeholder="输入编码或名称"/></el-form-item><el-form-item label="状态"><el-select v-model="status" clearable placeholder="全部状态"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item><el-button type="primary">查询</el-button><el-button @click="reset">重置</el-button></el-form></div><main class="surface tools-table"><div class="tools-table-head"><el-button type="primary" @click="openForm()">新增</el-button><span>{{ tabs.find(i=>i[0]===activeTab)?.[1] }}</span></div><el-table :data="currentRows"><el-table-column v-for="key in Object.keys(currentRows[0]||{})" :key="key" :prop="key" :label="({no:'编码/单号',code:'配置编码',name:'名称',target:'对象/接入信息',sign:'签名',template:'模板',time:'时间',status:'状态',provider:'供应商',audit:'审核状态',providerNo:'供应商编号',result:'结果',pieces:'计费条数',updated:'更新时间'} as any)[key]||key" min-width="130"/><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button link type="primary" @click="showDetail(row)">详情</el-button><el-button link type="primary" @click="openForm(row)">编辑</el-button></template></el-table-column></el-table></main></template>
<template v-else><div class="region-guide"><b>国家地区层级</b><span>国家</span><i>›</i><span>一级行政区：省、自治区、直辖市、特别行政区</span><i>›</i><span>二级行政区：地级市、自治州、地区、盟、市辖区</span></div><div class="surface tools-filter"><el-form inline><el-form-item label="地区名称/编码"><el-input v-model="keyword" clearable placeholder="请输入"/></el-form-item><el-form-item label="状态"><el-select v-model="status" clearable placeholder="全部状态"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item><el-button type="primary">查询</el-button><el-button @click="reset">重置</el-button></el-form></div><main class="surface tools-table"><div class="tools-table-head"><el-button type="primary" @click="openForm()">新增地区</el-button><span>地区编码接入国家地区标准数据源</span></div><el-table :data="regions" row-key="id" default-expand-all><el-table-column prop="name" label="国家/地区名称" min-width="220"/><el-table-column prop="code" label="标准编码" width="130"/><el-table-column prop="level" label="行政层级" width="140"><template #default="{row}"><el-tag :type="row.level==='COUNTRY'?'success':row.level==='LEVEL_1'?'primary':'info'">{{ row.level==='COUNTRY'?'国家':row.level==='LEVEL_1'?'一级行政区':'二级行政区' }}</el-tag></template></el-table-column><el-table-column prop="type" label="法定类型" min-width="230"/><el-table-column prop="status" label="状态" width="100"><template #default="{row}"><el-tag type="success">启用</el-tag></template></el-table-column><el-table-column label="操作" width="160"><template #default="{row}"><el-button link type="primary" @click="openForm(row)">编辑</el-button><el-button link type="primary" :disabled="row.level==='LEVEL_2'" @click="openForm()">新增下级</el-button></template></el-table-column></el-table></main></template>
<el-dialog v-model="dialog" :title="current.id?'编辑':'新增'" width="600px"><el-form label-position="top"><div class="form-grid"><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="编码/应用标识"><el-input v-model="form.app" placeholder="由对应服务校验唯一性"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status" style="width:100%"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select></el-form-item><el-form-item label="备注"><el-input v-model="form.remark"/></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="dialog=false;ElMessage.success('已保存')">保存</el-button></template></el-dialog><el-drawer v-model="drawer" title="详情" size="520px"><el-descriptions :column="1" border><el-descriptions-item v-for="(value,key) in current" :key="key" :label="String(key)">{{ value }}</el-descriptions-item></el-descriptions></el-drawer>
</section></template>
