<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import PageHeader from '../components/PageHeader.vue'
import '../styles/system-global-config.css'

type ParameterRow = {
  id:number; name:string; key:string; group:string; type:'STRING'|'NUMBER'|'BOOLEAN'|'JSON'|'SECRET'; value:string; status:string;
  sensitive:boolean; description:string; updatedAt:string; updatedBy:string; version:number
}

const storageKey='heshu_boss_system_parameters_v1'
const seed:ParameterRow[]=[
  {id:1,name:'客户默认归属保护天数',key:'customer.owner.protection_days',group:'客户规则',type:'NUMBER',value:'30',status:'ACTIVE',sensitive:false,description:'客户进入负责人名下后的默认保护周期，单位：天。',updatedAt:'2026-08-20 10:20:00',updatedBy:'张铭钰',version:3},
  {id:2,name:'线索批量任务单次上限',key:'lead.batch.max_size',group:'线索规则',type:'NUMBER',value:'5000',status:'ACTIVE',sensitive:false,description:'单次分配、同步或导出允许处理的最大线索数量。',updatedAt:'2026-08-20 09:45:18',updatedBy:'陈庆焕',version:2},
  {id:3,name:'登录密码最小长度',key:'security.password.min_length',group:'安全设置',type:'NUMBER',value:'8',status:'ACTIVE',sensitive:false,description:'账号密码允许设置的最小字符数。',updatedAt:'2026-08-19 18:10:00',updatedBy:'系统管理员',version:1},
  {id:4,name:'企微通讯录回调令牌',key:'wecom.callback.token',group:'集成设置',type:'SECRET',value:'WECOM_TOKEN_DEMO',status:'ACTIVE',sensitive:true,description:'企业微信通讯录回调验签令牌，仅授权管理员可更新。',updatedAt:'2026-08-19 16:42:08',updatedBy:'陈庆焕',version:4},
  {id:5,name:'手机号明文查看有效分钟',key:'privacy.mobile.reveal_minutes',group:'安全设置',type:'NUMBER',value:'10',status:'ACTIVE',sensitive:false,description:'完成授权后单次查看完整手机号的有效时长。',updatedAt:'2026-08-18 14:30:00',updatedBy:'张铭钰',version:2}
]
function loadRows(){try{return JSON.parse(localStorage.getItem(storageKey)||'null')||seed}catch{return seed}}
const rows=ref<ParameterRow[]>(loadRows()),keyword=ref(''),group=ref(''),status=ref(''),dialog=ref(false),historyDrawer=ref(false),editing=ref<ParameterRow|null>(null),current=ref<ParameterRow|null>(null)
const form=reactive<any>({name:'',key:'',group:'业务通用',type:'STRING',value:'',status:'ACTIVE',sensitive:false,description:''})
const groups=computed(()=>Array.from(new Set(rows.value.map(item=>item.group))))
const visible=computed(()=>rows.value.filter(item=>(!group.value||item.group===group.value)&&(!status.value||item.status===status.value)&&(!keyword.value||`${item.name}${item.key}${item.description}`.toLowerCase().includes(keyword.value.toLowerCase()))))
const activeCount=computed(()=>rows.value.filter(item=>item.status==='ACTIVE').length)
function persist(){localStorage.setItem(storageKey,JSON.stringify(rows.value))}
function reset(){keyword.value='';group.value='';status.value=''}
function openForm(row?:ParameterRow){editing.value=row||null;Object.assign(form,row||{name:'',key:'',group:'业务通用',type:'STRING',value:'',status:'ACTIVE',sensitive:false,description:''});if(row?.sensitive)form.value='';dialog.value=true}
function validateValue(){if(!form.name?.trim()||!form.key?.trim()||!form.group?.trim())return '请完整填写参数名称、参数键和参数分组';if(!editing.value&&!/^[a-z][a-z0-9_.-]{2,99}$/.test(form.key))return '参数键仅支持小写字母、数字、点、横线和下划线';if(!editing.value&&rows.value.some(item=>item.key===form.key))return '参数键已存在';if(form.type==='NUMBER'&&!/^[-+]?\d+(\.\d+)?$/.test(String(form.value)))return '参数值必须是数字';if(form.type==='BOOLEAN'&&!['true','false'].includes(String(form.value)))return '布尔值只能填写 true 或 false';if(!editing.value&&!String(form.value).trim())return '请输入参数值';return ''}
function save(){const error=validateValue();if(error){ElMessage.warning(error);return}const now=new Date().toLocaleString('zh-CN',{hour12:false});if(editing.value){const target=rows.value.find(item=>item.id===editing.value?.id)!;Object.assign(target,{...form,key:target.key,value:form.sensitive&&!form.value?target.value:form.value,updatedAt:now,updatedBy:'林校长',version:target.version+1})}else rows.value.unshift({...form,id:Date.now(),updatedAt:now,updatedBy:'林校长',version:1});persist();dialog.value=false;ElMessage.success(editing.value?'全局参数已更新':'全局参数已创建')}
async function toggle(row:ParameterRow){await ElMessageBox.confirm(`${row.status==='ACTIVE'?'停用':'启用'}后将影响所有引用该参数的功能。`,'确认变更全局参数？',{type:'warning'});row.status=row.status==='ACTIVE'?'INACTIVE':'ACTIVE';row.updatedAt=new Date().toLocaleString('zh-CN',{hour12:false});row.updatedBy='林校长';row.version++;persist();ElMessage.success(row.status==='ACTIVE'?'参数已启用':'参数已停用')}
function showHistory(row:ParameterRow){current.value=row;historyDrawer.value=true}
function displayValue(row:ParameterRow){return row.sensitive?'••••••••':row.type==='BOOLEAN'?(row.value==='true'?'是':'否'):row.value}
function parameterTypeLabel(type:string){return ({STRING:'文本',NUMBER:'数值',BOOLEAN:'开关',JSON:'JSON',SECRET:'密钥'} as Record<string,string>)[type]||type}
</script>

<template>
  <section class="page global-config-page">
    <PageHeader eyebrow="SYSTEM GOVERNANCE · GLOBAL SETTINGS" title="系统参数" description="统一维护影响合数BOSS全局行为的参数；所有变更记录版本、操作人和影响范围。"><el-button @click="ElMessage.info('已导出当前筛选下的参数清单，敏感值不会导出')">导出清单</el-button><el-button type="primary" @click="openForm()">新增参数</el-button></PageHeader>
    <div class="parameter-summary surface"><div><span>全局参数</span><b>{{ rows.length }}</b><small>已启用 {{ activeCount }} 项</small></div><p><strong>变更约束</strong> 参数键创建后不可修改；密钥类参数永不回显；修改立即对全局生效并写入审计日志。</p></div>
    <div class="surface global-filter"><el-input v-model="keyword" clearable prefix-icon="Search" placeholder="搜索参数名称、参数键或描述"/><el-select v-model="group" clearable placeholder="全部分组"><el-option v-for="item in groups" :key="item" :label="item" :value="item"/></el-select><el-select v-model="status" clearable placeholder="全部状态"><el-option label="启用" value="ACTIVE"/><el-option label="停用" value="INACTIVE"/></el-select><el-button type="primary">查询</el-button><el-button @click="reset">重置</el-button></div>
    <main class="surface global-table"><div class="global-table-title"><div><h2>参数列表</h2><span>共 {{ visible.length }} 项，参数值按类型校验</span></div><el-button type="primary" @click="openForm()">新增参数</el-button></div><el-table :data="visible" row-key="id"><el-table-column prop="name" label="参数名称" min-width="190"><template #default="{row}"><b class="primary-cell">{{ row.name }}</b><small>{{ row.description }}</small></template></el-table-column><el-table-column prop="key" label="参数键" min-width="230"><template #default="{row}"><code>{{ row.key }}</code></template></el-table-column><el-table-column prop="group" label="分组" width="112"/><el-table-column label="参数值" min-width="150"><template #default="{row}"><span :class="['parameter-value',{secret:row.sensitive}]">{{ displayValue(row) }}</span></template></el-table-column><el-table-column prop="type" label="类型" width="95"><template #default="{row}"><el-tag effect="plain">{{ parameterTypeLabel(row.type) }}</el-tag></template></el-table-column><el-table-column prop="status" label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{ row.status==='ACTIVE'?'启用':'停用' }}</el-tag></template></el-table-column><el-table-column label="最近更新" min-width="165"><template #default="{row}"><span>{{ row.updatedAt }}</span><small>{{ row.updatedBy }} · V{{ row.version }}</small></template></el-table-column><el-table-column label="操作" width="190" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openForm(row)">编辑</el-button><el-button link type="primary" @click="showHistory(row)">历史</el-button><el-button link :type="row.status==='ACTIVE'?'danger':'success'" @click="toggle(row)">{{ row.status==='ACTIVE'?'停用':'启用' }}</el-button></template></el-table-column></el-table><div class="global-pagination"><span>共 {{ visible.length }} 条</span><el-pagination background layout="prev,pager,next,sizes" :total="visible.length" :page-size="10"/></div></main>
    <el-dialog v-model="dialog" :title="editing?'编辑系统参数':'新增系统参数'" width="680px" destroy-on-close><el-alert title="系统参数面向全局生效，请优先使用字典管理维护可枚举的业务选项。" type="info" :closable="false" show-icon/><el-form label-position="top" class="global-form"><div class="form-grid"><el-form-item label="参数名称" required><el-input v-model="form.name" maxlength="50" placeholder="例如：客户默认归属保护天数"/></el-form-item><el-form-item label="参数分组" required><el-select v-model="form.group" filterable allow-create style="width:100%"><el-option v-for="item in groups" :key="item" :label="item" :value="item"/></el-select></el-form-item><el-form-item label="参数键" required><el-input v-model="form.key" :disabled="!!editing" placeholder="customer.owner.protection_days"/><small>保存后不可修改，建议使用“业务域.对象.含义”。</small></el-form-item><el-form-item label="参数类型" required><el-select v-model="form.type" :disabled="!!editing" style="width:100%"><el-option label="文本" value="STRING"/><el-option label="数值" value="NUMBER"/><el-option label="开关" value="BOOLEAN"/><el-option label="JSON" value="JSON"/><el-option label="密钥" value="SECRET"/></el-select></el-form-item><el-form-item label="参数值" required><el-select v-if="form.type==='BOOLEAN'" v-model="form.value" style="width:100%"><el-option label="是" value="true"/><el-option label="否" value="false"/></el-select><el-input v-else v-model="form.value" :type="form.type==='SECRET'?'password':'textarea'" :rows="form.type==='JSON'?4:2" :placeholder="editing&&form.sensitive?'留空表示不修改原密钥':'请输入参数值'" show-password/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio value="ACTIVE">启用</el-radio><el-radio value="INACTIVE">停用</el-radio></el-radio-group></el-form-item></div><el-form-item label="参数说明"><el-input v-model="form.description" type="textarea" :rows="3" maxlength="200" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存并生效</el-button></template></el-dialog>
    <el-drawer v-model="historyDrawer" title="参数变更历史" size="520px"><div v-if="current" class="history-context"><b>{{ current.name }}</b><code>{{ current.key }}</code></div><el-timeline><el-timeline-item :timestamp="current?.updatedAt" type="primary"><b>V{{ current?.version }} 当前版本</b><p>{{ current?.updatedBy }} 更新参数，敏感值不记录明文。</p></el-timeline-item><el-timeline-item timestamp="2026-08-18 09:30:00"><b>上一版本</b><p>系统管理员完成首次配置并启用。</p></el-timeline-item></el-timeline></el-drawer>
  </section>
</template>
